export type CuratedBudgetArchiveSourceType =
  | 'cyprus_budget_archive'
  | 'hungary_budget_archive'
  | 'malta_budget_archive'
  | 'nrsr_sk';

export interface CuratedBudgetArchiveRecord {
  countryCode: 'CY' | 'HU' | 'MT' | 'SK';
  countryName: string;
  dataSource: CuratedBudgetArchiveSourceType;
  sourceUrl: string;
  title: string;
  officialTitle: string;
  submittedDate: string;
  voteDate: string | null;
  status: 'consultation' | 'adopted';
  sponsors: string[];
  summary: string;
}

export const CURATED_BUDGET_ARCHIVES: CuratedBudgetArchiveRecord[] = [
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    dataSource: 'cyprus_budget_archive',
    sourceUrl: 'https://www.parliament.cy/el/%CE%BD%CE%BF%CE%BC%CE%BF%CE%B8%CE%B5%CF%84%CE%B9%CE%BA%CF%8C-%CE%AD%CF%81%CE%B3%CE%BF/%CE%BA%CE%B1%CF%84%CE%AC%CE%B8%CE%B5%CF%83%CE%B7-%CE%BD%CE%BF%CE%BC%CE%BF%CF%83%CF%87%CE%B5%CE%B4%CE%AF%CF%89%CE%BD-%CE%BA%CE%B1%CE%B9-%CE%B5%CE%B3%CE%B3%CF%81%CE%AC%CF%86%CF%89%CE%BD/%CE%BA%CE%B1%CF%84%CE%AC%CE%B8%CE%B5%CF%83%CE%B7-%CE%BD%CE%BF%CE%BC%CE%BF%CF%83%CF%87%CE%B5%CE%B4%CE%AF%CF%89%CE%BD-%CE%BA%CE%B1%CE%B9-%CE%B5%CE%B3%CE%B3%CF%81%CE%AC%CF%86%CF%89%CE%BD-2024/%CF%83%CF%85%CE%BD%CE%B5%CE%B4%CF%81%CE%AF%CE%B1-%CE%BF%CE%BB%CE%BF%CE%BC%CE%AD%CE%BB%CE%B5%CE%B9%CE%B1%CF%82-03102024/%CE%BD%CE%BF%CE%BC%CE%BF%CF%83%CF%87%CE%AD%CE%B4%CE%B9%CE%B1/23.01.065.176-2024-%CE%BF-%CF%80%CE%B5%CF%81%CE%AF-%CF%80%CF%81%CE%BF%CF%8B%CF%80%CE%BF%CE%BB%CE%BF%CE%B3%CE%B9%CF%83%CE%BC%CE%BF%CF%8D-%CF%84%CE%BF%CF%85-2025-%CE%BD%CF%8C%CE%BC%CE%BF%CF%82-%CF%84%CE%BF%CF%85-2024',
    title: 'Cyprus budget law 2025',
    officialTitle: 'Ο περί Προϋπολογισμού του 2025 Νόμος του 2024',
    submittedDate: '2024-10-03',
    voteDate: null,
    status: 'consultation',
    sponsors: ['Υπουργείο Οικονομικών'],
    summary: 'Official House of Representatives deposit page for the 2025 state budget law, tabled in plenary on 2024-10-03.',
  },
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    dataSource: 'cyprus_budget_archive',
    sourceUrl: 'https://www.parliament.cy/el/%CE%BD%CE%BF%CE%BC%CE%BF%CE%B8%CE%B5%CF%84%CE%B9%CE%BA%CF%8C-%CE%AD%CF%81%CE%B3%CE%BF/%CE%BA%CE%B1%CF%84%CE%AC%CE%B8%CE%B5%CF%83%CE%B7-%CE%BD%CE%BF%CE%BC%CE%BF%CF%83%CF%87%CE%B5%CE%B4%CE%AF%CF%89%CE%BD-%CE%BA%CE%B1%CE%B9-%CE%B5%CE%B3%CE%B3%CF%81%CE%AC%CF%86%CF%89%CE%BD/%CE%BA%CE%B1%CF%84%CE%AC%CE%B8%CE%B5%CF%83%CE%B7-%CE%BD%CE%BF%CE%BC%CE%BF%CF%83%CF%87%CE%B5%CE%B4%CE%AF%CF%89%CE%BD-%CE%BA%CE%B1%CE%B9-%CE%B5%CE%B3%CE%B3%CF%81%CE%AC%CF%86%CF%89%CE%BD-2025/%CF%83%CF%85%CE%BD%CE%B5%CE%B4%CF%81%CE%AF%CE%B1-%CE%BF%CE%BB%CE%BF%CE%BC%CE%AD%CE%BB%CE%B5%CE%B9%CE%B1%CF%82-02102025/%CE%BD%CE%BF%CE%BC%CE%BF%CF%83%CF%87%CE%AD%CE%B4%CE%B9%CE%B1/23.01.066.224-2025-%CE%BF-%CF%80%CE%B5%CF%81%CE%AF-%CF%80%CF%81%CE%BF%CF%8B%CF%80%CE%BF%CE%BB%CE%BF%CE%B3%CE%B9%CF%83%CE%BC%CE%BF%CF%8D-%CF%84%CE%BF%CF%85-2026-%CE%BD%CF%8C%CE%BC%CE%BF%CF%82-%CF%84%CE%BF%CF%85-2025',
    title: 'Cyprus budget law 2026',
    officialTitle: 'Ο περί Προϋπολογισμού του 2026 Νόμος του 2025',
    submittedDate: '2025-10-02',
    voteDate: null,
    status: 'consultation',
    sponsors: ['Υπουργείο Οικονομικών'],
    summary: 'Official House of Representatives deposit page for the 2026 state budget law, tabled in plenary on 2025-10-02.',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    dataSource: 'hungary_budget_archive',
    sourceUrl: 'https://www.parlament.hu/irom41/16118/16118.pdf',
    title: 'Hungary central budget 2022',
    officialTitle: 'Magyarország 2022. évi központi költségvetéséről',
    submittedDate: '2021-05-04',
    voteDate: null,
    status: 'adopted',
    sponsors: ['kormány (pénzügyminiszter)'],
    summary: 'Official Országgyűlés budget-bill PDF T/16118 for Hungary’s 2022 central budget; the iromány record lists submission on 2021-05-04.',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    dataSource: 'hungary_budget_archive',
    sourceUrl: 'https://www.parlament.hu/irom42/00152/00152.pdf',
    title: 'Hungary central budget 2023',
    officialTitle: 'Magyarország 2023. évi központi költségvetéséről',
    submittedDate: '2022-06-07',
    voteDate: '2022-07-27',
    status: 'adopted',
    sponsors: ['kormány (pénzügyminiszter)'],
    summary: 'Official Országgyűlés budget-bill PDF T/152 for Hungary’s 2023 central budget; the iromány record shows submission on 2022-06-07 and promulgation as 2022. évi XXV. törvény on 2022-07-27.',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    dataSource: 'hungary_budget_archive',
    sourceUrl: 'https://www.parlament.hu/irom42/04181/04181.pdf',
    title: 'Hungary central budget 2024',
    officialTitle: 'Magyarország 2024. évi központi költségvetéséről',
    submittedDate: '2023-05-30',
    voteDate: null,
    status: 'adopted',
    sponsors: ['kormány (pénzügyminiszter)'],
    summary: 'Official Országgyűlés budget-bill PDF T/4181 for Hungary’s 2024 central budget; the PDF cover records submission on 2023-05-30 10:18.',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    dataSource: 'hungary_budget_archive',
    sourceUrl: 'https://www.parlament.hu/irom42/09894/09894.pdf',
    title: 'Hungary central budget 2025',
    officialTitle: 'Magyarország 2025. évi központi költségvetéséről',
    submittedDate: '2024-11-11',
    voteDate: null,
    status: 'adopted',
    sponsors: ['kormány (pénzügyminiszter)'],
    summary: 'Official Országgyűlés budget-bill PDF T/9894 for Hungary’s 2025 central budget; the PDF cover records submission on 2024-11-11 16:00.',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    dataSource: 'hungary_budget_archive',
    sourceUrl: 'https://www.parlament.hu/irom42/11864/11864.pdf',
    title: 'Hungary central budget 2026',
    officialTitle: 'Magyarország 2026. évi központi költségvetéséről',
    submittedDate: '2025-05-06',
    voteDate: null,
    status: 'adopted',
    sponsors: ['kormány (nemzetgazdasági miniszter)'],
    summary: 'Official Országgyűlés budget-bill PDF T/11864 for Hungary’s 2026 central budget; the PDF cover records submission on 2025-05-06 20:06.',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    dataSource: 'malta_budget_archive',
    sourceUrl: 'https://www.parlament.mt/13th-leg/bills/bill-no-173-budget-measures-implementation-bill/',
    title: 'Malta budget measures 2021',
    officialTitle: 'Budget Measures Implementation Bill',
    submittedDate: '2020-10-19',
    voteDate: '2021-04-14',
    status: 'adopted',
    sponsors: ['Government of Malta'],
    summary: 'Official Parliament of Malta bill page for Bill No. 173, implementing budget measures for financial year 2021; first reading on 2020-10-19 and third reading completed in April 2021.',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    dataSource: 'malta_budget_archive',
    sourceUrl: 'https://parlament.mt/13th-leg/acts/act-vii-of-2022/',
    title: 'Malta budget measures 2022',
    officialTitle: 'Budget Measures Implementation Bill',
    submittedDate: '2021-10-11',
    voteDate: '2022-02-02',
    status: 'adopted',
    sponsors: ['Government of Malta'],
    summary: 'Official Parliament of Malta act page for Act No. VII of 2022 / Bill No. 247, implementing budget measures for financial year 2022; published on 2022-02-08.',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    dataSource: 'malta_budget_archive',
    sourceUrl: 'https://www.parlament.mt/14th-leg/acts/act-xii-of-2023/',
    title: 'Malta budget measures 2023',
    officialTitle: 'Budget Measures Implementation Bill',
    submittedDate: '2022-10-24',
    voteDate: '2023-03-29',
    status: 'adopted',
    sponsors: ['Government of Malta'],
    summary: 'Official Parliament of Malta act page for Act No. XII of 2023 / Bill No. 24, implementing budget measures for financial year 2023; published on 2023-04-04.',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    dataSource: 'malta_budget_archive',
    sourceUrl: 'https://parlament.mt/14th-leg/acts/act-xiii-of-2024/',
    title: 'Malta budget measures 2024',
    officialTitle: 'Budget Measures Implementation Bill',
    submittedDate: '2023-10-30',
    voteDate: '2024-03-27',
    status: 'adopted',
    sponsors: ['Government of Malta'],
    summary: 'Official Parliament of Malta act page for Act No. XIII of 2024 / Bill No. 72, implementing budget measures for financial year 2024; published on 2024-04-02.',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    dataSource: 'malta_budget_archive',
    sourceUrl: 'https://parlament.mt/14th-leg/bills/bill-117-budget-measures-implementation/',
    title: 'Malta budget measures 2025',
    officialTitle: 'Budget Measures Implementation Bill',
    submittedDate: '2024-10-28',
    voteDate: '2025-04-14',
    status: 'adopted',
    sponsors: ['Government of Malta'],
    summary: 'Official Parliament of Malta bill page for Bill No. 117, implementing budget measures for financial year 2025; the page lists first reading on 2024-10-28 and Act No. IX of 2025 after third reading in April 2025.',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    dataSource: 'malta_budget_archive',
    sourceUrl: 'https://parlament.mt/14th-leg/bills/bill-155-budget-measures-implementation-bill/',
    title: 'Malta budget measures 2026',
    officialTitle: 'Budget Measures Implementation Bill',
    submittedDate: '2025-10-27',
    voteDate: '2026-03-03',
    status: 'adopted',
    sponsors: ['Government of Malta'],
    summary: 'Official Parliament of Malta bill page for Bill No. 155, implementing budget measures for financial year 2026; the page lists first reading on 2025-10-27 and Act No. III of 2026 after third reading on 2026-03-03.',
  },
  {
    countryCode: 'SK',
    countryName: 'Slovakia',
    dataSource: 'nrsr_sk',
    sourceUrl: 'https://www.nrsr.sk/web/Default.aspx?sid=zakony/zakon&MasterID=10146',
    title: 'Slovakia state budget 2025',
    officialTitle: 'Návrh zákona o štátnom rozpočte na rok 2025',
    submittedDate: '2024-10-10',
    voteDate: '2025-01-17',
    status: 'adopted',
    sponsors: ['vláda Slovenskej republiky'],
    summary: 'Official NRSR legislative detail page for the 2025 state budget bill (MasterID 10146), submitted on 2024-10-10 and approved on 2025-01-17.',
  },
];

export function buildProposalFromCuratedBudgetArchive(record: CuratedBudgetArchiveRecord) {
  return {
    title: record.title.slice(0, 500),
    official_title: record.officialTitle,
    status: record.status,
    proposal_type: 'budget',
    jurisdiction: 'federal',
    country_code: record.countryCode,
    country_name: record.countryName,
    vote_date: record.voteDate,
    submitted_date: record.submittedDate,
    sponsors: record.sponsors,
    affected_laws: [],
    evidence_count: 1,
    summary: record.summary,
    policy_area: 'finance',
    source_url: record.sourceUrl,
    data_source: record.dataSource,
  };
}
