import type { CountryPoliticalProfile } from '@/lib/political-system-profiles';

export const portugalProfile: CountryPoliticalProfile = {
  countryCode: 'PT',
  countryName: 'Portugal',
  systemSummary:
    'Unitary semi-presidential republic where a directly elected President coexists with a Prime Minister and Government responsible before the Assembly of the Republic.',
  diagrams: [
    {
      id: 'master_system',
      title: 'Master System Diagram',
      purpose:
        'High-level map of electoral legitimacy, executive dualism, legislative authority, constitutional justice, and local administration.',
      level: 1,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'president', label: 'President of the Republic', category: 'Executive Office' },
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislative Chamber' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'government', label: 'Government (Council of Ministers)', category: 'Executive Office' },
        { id: 'constCourt', label: 'Constitutional Court', category: 'Court' },
        { id: 'municipalities', label: 'Municipalities and Parishes', category: 'Subnational Government' },
      ],
      edges: [
        { from: 'voters', to: 'president', label: 'elect directly', layer: 'de_jure' },
        { from: 'voters', to: 'assembly', label: 'elect deputies', layer: 'de_jure' },
        { from: 'president', to: 'pm', label: 'appoints', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'proposes ministers', layer: 'de_jure' },
        { from: 'president', to: 'government', label: 'appoints ministers', layer: 'de_jure' },
        { from: 'assembly', to: 'government', label: 'political oversight and censure', layer: 'de_jure' },
        { from: 'constCourt', to: 'assembly', label: 'constitutional review of legislation', layer: 'de_jure' },
      ],
      notes: ['Portugal combines parliamentary responsibility with an independently elected head of state.'],
      sources: [
        { title: 'Constitution of the Portuguese Republic (English)', url: 'https://www.parlamento.pt/sites/EN/Parliament/Documents/Constitution7th.pdf' },
        { title: 'Presidency of the Portuguese Republic', url: 'https://www.presidencia.pt/' },
        { title: 'Assembly of the Republic - Role and Competences', url: 'https://www.parlamento.pt/sites/EN/Parliament/Paginas/RoleCompetences.aspx' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'selection_appointment',
      title: 'Selection and Appointment Diagram',
      purpose: 'How Portugal fills the presidency, parliament, government, and constitutional court bench.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislative Chamber' },
        { id: 'president', label: 'President of the Republic', category: 'Executive Office' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'government', label: 'Government Ministers', category: 'Executive Office' },
        { id: 'constCourt', label: 'Constitutional Court Judges', category: 'Court' },
      ],
      edges: [
        { from: 'voters', to: 'president', label: 'elect by direct vote', layer: 'de_jure' },
        { from: 'voters', to: 'assembly', label: 'elect by party lists', layer: 'de_jure' },
        { from: 'president', to: 'pm', label: 'appoints after hearing parties', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'proposes ministers/secretaries', layer: 'de_jure' },
        { from: 'president', to: 'government', label: 'formally appoints', layer: 'de_jure' },
        { from: 'assembly', to: 'constCourt', label: 'elects constitutional judges', layer: 'de_jure' },
      ],
      notes: ['Government formation is presidentially formalized but parliamentary viability is decisive.'],
      sources: [
        { title: 'Constitution of the Portuguese Republic (English)', url: 'https://www.parlamento.pt/sites/EN/Parliament/Documents/Constitution7th.pdf' },
        { title: 'Portuguese Constitutional Court', url: 'https://www.tribunalconstitucional.pt/tc/en/tribunal.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'lawmaking',
      title: 'Lawmaking Diagram',
      purpose: 'Legislative initiation, parliamentary adoption, presidential promulgation, and constitutional control.',
      level: 2,
      nodes: [
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'deputies', label: 'Deputies/Parliamentary Groups', category: 'Legislature' },
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislative Chamber' },
        { id: 'president', label: 'President of the Republic', category: 'Executive Office' },
        { id: 'constCourt', label: 'Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'government', to: 'assembly', label: 'submits bills/proposals', layer: 'de_jure' },
        { from: 'deputies', to: 'assembly', label: 'introduce bills', layer: 'de_jure' },
        { from: 'assembly', to: 'president', label: 'sends approved decree for promulgation', layer: 'de_jure' },
        { from: 'president', to: 'assembly', label: 'political veto and return', layer: 'de_jure' },
        { from: 'president', to: 'constCourt', label: 'requests preventive review', layer: 'de_jure' },
        { from: 'constCourt', to: 'president', label: 'rules on constitutionality', layer: 'de_jure' },
      ],
      notes: ['Portugal is unicameral, so main veto points are presidential and constitutional.'],
      sources: [
        { title: 'Assembly of the Republic - Legislative Procedure', url: 'https://www.parlamento.pt/sites/EN/Parliament/Paginas/LegislativeProcess.aspx' },
        { title: 'Constitution of the Portuguese Republic (English)', url: 'https://www.parlamento.pt/sites/EN/Parliament/Documents/Constitution7th.pdf' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'government_formation',
      title: 'Government Formation Diagram',
      purpose: 'How election outcomes, party bargaining, and presidential appointment produce an executive.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'parties', label: 'Political Parties', category: 'Political Party' },
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislative Chamber' },
        { id: 'president', label: 'President of the Republic', category: 'Executive Office' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
      ],
      edges: [
        { from: 'voters', to: 'parties', label: 'allocate vote shares', layer: 'de_facto' },
        { from: 'parties', to: 'assembly', label: 'convert votes into seats', layer: 'de_jure' },
        { from: 'parties', to: 'pm', label: 'coalition/accord negotiations shape candidate', layer: 'de_facto' },
        { from: 'president', to: 'pm', label: 'appoints after hearing parties', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'proposes cabinet composition', layer: 'de_jure' },
        { from: 'assembly', to: 'government', label: 'can reject program and force resignation', layer: 'de_jure' },
      ],
      notes: ['Minority governments are common and depend on negotiated parliamentary support.'],
      sources: [
        { title: 'Constitution of the Portuguese Republic (English)', url: 'https://www.parlamento.pt/sites/EN/Parliament/Documents/Constitution7th.pdf' },
        { title: 'Presidency - Constitutional Competences', url: 'https://www.presidencia.pt/presidente-da-republica/competencias/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'oversight_removal',
      title: 'Oversight and Removal Diagram',
      purpose: 'How parliament, audit institutions, and constitutional adjudication constrain executive power.',
      level: 2,
      nodes: [
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislative Chamber' },
        { id: 'committees', label: 'Parliamentary Committees', category: 'Legislature' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'auditCourt', label: 'Court of Auditors', category: 'Independent Agency' },
        { id: 'constCourt', label: 'Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'assembly', to: 'government', label: 'motions of censure/confidence', layer: 'de_jure' },
        { from: 'assembly', to: 'committees', label: 'creates inquiries', layer: 'de_jure' },
        { from: 'committees', to: 'pm', label: 'hearings and questioning', layer: 'de_jure' },
        { from: 'committees', to: 'government', label: 'investigative scrutiny', layer: 'de_jure' },
        { from: 'auditCourt', to: 'government', label: 'audits expenditure legality', layer: 'de_jure' },
        { from: 'constCourt', to: 'government', label: 'annuls unconstitutional norms', layer: 'de_jure' },
      ],
      notes: ['Executive survival hinges on parliamentary confidence dynamics.'],
      sources: [
        { title: 'Assembly of the Republic - Oversight Powers', url: 'https://www.parlamento.pt/sites/EN/Parliament/Paginas/RoleCompetences.aspx' },
        { title: 'Portuguese Court of Auditors', url: 'https://www.tcontas.pt/en/' },
        { title: 'Portuguese Constitutional Court', url: 'https://www.tribunalconstitucional.pt/tc/en/home.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'judicial_review',
      title: 'Judicial and Constitutional Review Diagram',
      purpose: 'Portuguese constitutional review pathways (preventive, abstract, and concrete review).',
      level: 2,
      nodes: [
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'ombudsman', label: 'Ombudsman', category: 'Independent Agency' },
        { id: 'ordinaryCourts', label: 'Ordinary Courts', category: 'Court' },
        { id: 'constCourt', label: 'Constitutional Court', category: 'Court' },
        { id: 'assembly', label: 'Assembly', category: 'Legislature' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
      ],
      edges: [
        { from: 'president', to: 'constCourt', label: 'requests review', layer: 'de_jure' },
        { from: 'ombudsman', to: 'constCourt', label: 'requests abstract review', layer: 'de_jure' },
        { from: 'ordinaryCourts', to: 'constCourt', label: 'appeals constitutional issues', layer: 'de_jure' },
        { from: 'constCourt', to: 'assembly', label: 'invalidates statutes', layer: 'de_jure' },
        { from: 'constCourt', to: 'government', label: 'invalidates decrees', layer: 'de_jure' },
      ],
      notes: ['Constitutionality control is concentrated in the Constitutional Court.'],
      sources: [
        { title: 'Constitution of the Portuguese Republic (English)', url: 'https://www.parlamento.pt/sites/EN/Parliament/Documents/Constitution7th.pdf' },
        { title: 'Portuguese Constitutional Court - Jurisdiction', url: 'https://www.tribunalconstitucional.pt/tc/en/tribunal.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'election_representation',
      title: 'Election and Representation Diagram',
      purpose: 'How votes are translated into seats through district-based proportional representation.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'partyLists', label: 'Party Lists', category: 'Political Party' },
        { id: 'districts', label: 'Electoral Districts', category: 'Subnational Government' },
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislative Chamber' },
        { id: 'electoralAdmin', label: 'Election Administration', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'voters', to: 'partyLists', label: 'cast list votes', layer: 'de_jure' },
        { from: 'partyLists', to: 'districts', label: 'compete in multi-member districts', layer: 'de_jure' },
        { from: 'districts', to: 'assembly', label: 'allocate seats by D’Hondt', layer: 'de_jure' },
        { from: 'electoralAdmin', to: 'assembly', label: 'certifies mandates', layer: 'de_jure' },
      ],
      notes: ['District magnitude and D’Hondt mechanics favor larger parties in smaller circles.'],
      sources: [
        { title: 'National Election Commission (CNE)', url: 'https://www.cne.pt/' },
        { title: 'Electoral Law for the Assembly', url: 'https://www.cne.pt/content/lei-eleitoral-para-assembleia-da-republica' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'territorial_federalism',
      title: 'Territorial and Regional Autonomy Diagram',
      purpose: 'Unitary state with autonomous regions and local self-government.',
      level: 2,
      nodes: [
        { id: 'republic', label: 'Portuguese Republic', category: 'Executive Office' },
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislature' },
        { id: 'azores', label: 'Azores', category: 'Subnational Government' },
        { id: 'madeira', label: 'Madeira', category: 'Subnational Government' },
        { id: 'municipalities', label: 'Municipalities/Parishes', category: 'Subnational Government' },
        { id: 'constCourt', label: 'Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'assembly', to: 'azores', label: 'defines autonomy framework', layer: 'de_jure' },
        { from: 'assembly', to: 'madeira', label: 'defines autonomy framework', layer: 'de_jure' },
        { from: 'republic', to: 'municipalities', label: 'sets local-government framework', layer: 'de_jure' },
        { from: 'constCourt', to: 'azores', label: 'adjudicates autonomy disputes', layer: 'de_jure' },
        { from: 'constCourt', to: 'madeira', label: 'adjudicates autonomy disputes', layer: 'de_jure' },
      ],
      notes: ['Portugal is not federal; autonomy is entrenched for two island regions.'],
      sources: [
        { title: 'Constitution of the Portuguese Republic (English)', url: 'https://www.parlamento.pt/sites/EN/Parliament/Documents/Constitution7th.pdf' },
        { title: 'Government of Portugal - Local Administration', url: 'https://www.portugal.gov.pt/en/gc23/ministries/presidency/secretary-of-state-for-local-administration-and-territorial-planning' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'budget_finance',
      title: 'Budget and Public Finance Diagram',
      purpose: 'Budget drafting, parliamentary approval, execution, and external control.',
      level: 2,
      nodes: [
        { id: 'taxpayers', label: 'Taxpayers', category: 'Voters / Citizens' },
        { id: 'financeMin', label: 'Ministry of Finance', category: 'Ministry / Department' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'assembly', label: 'Assembly of the Republic', category: 'Legislative Chamber' },
        { id: 'auditCourt', label: 'Court of Auditors', category: 'Independent Agency' },
        { id: 'euroCommission', label: 'European Commission', category: 'International Actor' },
      ],
      edges: [
        { from: 'taxpayers', to: 'financeMin', label: 'provide tax revenues', layer: 'de_jure' },
        { from: 'financeMin', to: 'government', label: 'prepares draft budget', layer: 'de_jure' },
        { from: 'government', to: 'assembly', label: 'submits annual budget bill', layer: 'de_jure' },
        { from: 'assembly', to: 'government', label: 'approves/amends appropriations', layer: 'de_jure' },
        { from: 'auditCourt', to: 'assembly', label: 'reports budget execution', layer: 'de_jure' },
        { from: 'euroCommission', to: 'government', label: 'EU fiscal surveillance', layer: 'de_jure' },
      ],
      notes: ['National budgeting operates within EU fiscal coordination constraints.'],
      sources: [
        { title: 'Portuguese Ministry of Finance', url: 'https://www.portugal.gov.pt/en/gc23/ministries/finance' },
        { title: 'Portuguese Court of Auditors', url: 'https://www.tcontas.pt/en/' },
        { title: 'European Semester - Portugal', url: 'https://economy-finance.ec.europa.eu/economic-surveillance-eu-economies/portugal/economic-forecast-portugal_en' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'de_facto_power',
      title: 'De Facto Power Map',
      purpose: 'Practical influence channels beyond formal constitutional allocation.',
      level: 2,
      nodes: [
        { id: 'partyLeadership', label: 'Major Party Leaderships', category: 'Political Party' },
        { id: 'parliamentGroups', label: 'Parliamentary Groups', category: 'Legislature' },
        { id: 'pmOffice', label: 'Prime Minister’s Office', category: 'Executive Office' },
        { id: 'presidentOffice', label: 'Presidential Office', category: 'Executive Office' },
        { id: 'socialPartners', label: 'Unions and Employer Groups', category: 'Independent Agency' },
        { id: 'publicOpinion', label: 'Media and Public Opinion', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'partyLeadership', to: 'parliamentGroups', label: 'candidate control and vote discipline', layer: 'de_facto' },
        { from: 'parliamentGroups', to: 'pmOffice', label: 'support agreements condition agenda', layer: 'de_facto' },
        { from: 'presidentOffice', to: 'pmOffice', label: 'agenda signaling and dissolution leverage', layer: 'de_facto' },
        { from: 'socialPartners', to: 'pmOffice', label: 'concertation pressure', layer: 'de_facto' },
        { from: 'publicOpinion', to: 'partyLeadership', label: 'electoral and reputational pressure', layer: 'de_facto' },
      ],
      notes: ['Confidence: medium-high. Fragmentation increases bargaining leverage of support partners.'],
      sources: [
        { title: 'Presidency of the Portuguese Republic', url: 'https://www.presidencia.pt/' },
        { title: 'Assembly of the Republic', url: 'https://www.parlamento.pt/sites/EN/Pages/default.aspx' },
        { title: 'Economic and Social Council of Portugal', url: 'https://www.ces.pt/' },
      ],
      lastUpdated: '2026-04-21',
    },
  ],
};

export const spainProfile: CountryPoliticalProfile = {
  countryCode: 'ES',
  countryName: 'Spain',
  systemSummary:
    'Parliamentary constitutional monarchy with bicameral Cortes Generales, confidence-based government, autonomous communities, and concentrated constitutional review.',
  diagrams: [
    {
      id: 'master_system',
      title: 'Master System Diagram',
      purpose: 'High-level map of the Crown, Cortes Generales, Government, Constitutional Court, and autonomous communities.',
      level: 1,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'congress', label: 'Congress of Deputies', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'king', label: 'King', category: 'Monarchical / Religious Actor' },
        { id: 'pm', label: 'President of the Government', category: 'Executive Office' },
        { id: 'government', label: 'Council of Ministers', category: 'Executive Office' },
        { id: 'tc', label: 'Constitutional Court', category: 'Court' },
        { id: 'ccaa', label: 'Autonomous Communities', category: 'Subnational Government' },
      ],
      edges: [
        { from: 'voters', to: 'congress', label: 'elects', layer: 'de_jure' },
        { from: 'voters', to: 'senate', label: 'elects most senators', layer: 'de_jure' },
        { from: 'congress', to: 'pm', label: 'investiture confidence', layer: 'de_jure' },
        { from: 'king', to: 'pm', label: 'formally appoints', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'proposes ministers', layer: 'de_jure' },
        { from: 'king', to: 'government', label: 'formally appoints ministers', layer: 'de_jure' },
        { from: 'tc', to: 'government', label: 'constitutional review', layer: 'de_jure' },
      ],
      notes: ['Constitutional monarchy where democratic legitimacy flows through parliamentary confidence.'],
      sources: [
        { title: 'Spanish Constitution (English)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'Congress of Deputies', url: 'https://www.congreso.es/en/cem/funciones' },
        { title: 'Constitutional Court of Spain', url: 'https://www.tribunalconstitucional.es/en/Paginas/default.aspx' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'selection_appointment',
      title: 'Selection and Appointment Diagram',
      purpose: 'How Spain selects parliament, forms the premiership, and appoints constitutional actors.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'congress', label: 'Congress of Deputies', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'king', label: 'King', category: 'Monarchical / Religious Actor' },
        { id: 'pm', label: 'President of the Government', category: 'Executive Office' },
        { id: 'tc', label: 'Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'voters', to: 'congress', label: 'elects deputies', layer: 'de_jure' },
        { from: 'voters', to: 'senate', label: 'elects senators', layer: 'de_jure' },
        { from: 'king', to: 'congress', label: 'proposes investiture candidate', layer: 'de_jure' },
        { from: 'congress', to: 'pm', label: 'invests by confidence vote', layer: 'de_jure' },
        { from: 'king', to: 'pm', label: 'appoints after investiture', layer: 'de_jure' },
        { from: 'congress', to: 'tc', label: 'elects magistrates share', layer: 'de_jure' },
        { from: 'senate', to: 'tc', label: 'elects magistrates share', layer: 'de_jure' },
      ],
      notes: ['Government formation is impossible without explicit congressional investiture.'],
      sources: [
        { title: 'Spanish Constitution (Arts. 62, 99, 159)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'Organic Law 2/1979 on the Constitutional Court', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-1979-23709' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'lawmaking',
      title: 'Lawmaking Diagram',
      purpose: 'Ordinary legislative process across both chambers with final promulgation.',
      level: 2,
      nodes: [
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'congress', label: 'Congress of Deputies', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'king', label: 'King', category: 'Monarchical / Religious Actor' },
        { id: 'tc', label: 'Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'government', to: 'congress', label: 'submits bills', layer: 'de_jure' },
        { from: 'congress', to: 'senate', label: 'passes and transmits', layer: 'de_jure' },
        { from: 'senate', to: 'congress', label: 'amends or vetoes', layer: 'de_jure' },
        { from: 'congress', to: 'senate', label: 'can override veto', layer: 'de_jure' },
        { from: 'king', to: 'congress', label: 'sanctions and promulgates law', layer: 'de_jure' },
        { from: 'tc', to: 'congress', label: 'annuls unconstitutional norms', layer: 'de_jure' },
      ],
      notes: ['Congress is decisive when bicameral conflict persists.'],
      sources: [
        { title: 'Spanish Constitution (Arts. 87-92)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'Congress - Legislative Procedure', url: 'https://www.congreso.es/en/cem/funcion-legislativa' },
        { title: 'Senate - Legislative Function', url: 'https://www.senado.es/web/conocersenado/temasclave/funcionesdelsenado/index.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'government_formation',
      title: 'Government Formation Diagram',
      purpose: 'How election results and party bargaining translate into an investiture-backed government.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'parties', label: 'Political Parties', category: 'Political Party' },
        { id: 'congress', label: 'Congress of Deputies', category: 'Legislative Chamber' },
        { id: 'king', label: 'King', category: 'Monarchical / Religious Actor' },
        { id: 'pm', label: 'President of the Government', category: 'Executive Office' },
        { id: 'government', label: 'Council of Ministers', category: 'Executive Office' },
      ],
      edges: [
        { from: 'voters', to: 'parties', label: 'allocates vote share', layer: 'de_facto' },
        { from: 'parties', to: 'congress', label: 'wins seats', layer: 'de_jure' },
        { from: 'parties', to: 'pm', label: 'coalition/accord bargaining', layer: 'de_facto' },
        { from: 'king', to: 'congress', label: 'consults and proposes candidate', layer: 'de_jure' },
        { from: 'congress', to: 'pm', label: 'grants or denies confidence', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'selects ministers', layer: 'de_jure' },
      ],
      notes: ['Failed investitures can trigger dissolution and new elections.'],
      sources: [
        { title: 'Spanish Constitution (Art. 99)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'Royal Household - Constitutional Functions', url: 'https://www.casareal.es/ES/Corona/Paginas/subhome_corona.aspx' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'oversight_removal',
      title: 'Oversight and Removal Diagram',
      purpose: 'Parliamentary control, audit institutions, and no-confidence/removal mechanisms.',
      level: 2,
      nodes: [
        { id: 'congress', label: 'Congress of Deputies', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'pm', label: 'President of the Government', category: 'Executive Office' },
        { id: 'audit', label: 'Court of Auditors', category: 'Independent Agency' },
        { id: 'tc', label: 'Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'congress', to: 'government', label: 'questions and inquiries', layer: 'de_jure' },
        { from: 'congress', to: 'pm', label: 'constructive motion of censure', layer: 'de_jure' },
        { from: 'pm', to: 'congress', label: 'confidence vote request', layer: 'de_jure' },
        { from: 'senate', to: 'government', label: 'scrutiny and committee oversight', layer: 'de_jure' },
        { from: 'audit', to: 'government', label: 'external financial audit', layer: 'de_jure' },
        { from: 'tc', to: 'government', label: 'constitutional constraints', layer: 'de_jure' },
      ],
      notes: ['Constructive no-confidence requires naming a replacement PM candidate.'],
      sources: [
        { title: 'Spanish Constitution (Arts. 108-116)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'Court of Auditors (Tribunal de Cuentas)', url: 'https://www.tcu.es/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'judicial_review',
      title: 'Judicial and Constitutional Review Diagram',
      purpose: 'Centralized constitutional review and referral channels.',
      level: 2,
      nodes: [
        { id: 'ordinaryCourts', label: 'Ordinary Courts', category: 'Court' },
        { id: 'supremeCourt', label: 'Supreme Court', category: 'Court' },
        { id: 'tc', label: 'Constitutional Court', category: 'Court' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'parliament', label: 'Cortes Generales', category: 'Legislature' },
        { id: 'ccaa', label: 'Autonomous Communities', category: 'Subnational Government' },
      ],
      edges: [
        { from: 'ordinaryCourts', to: 'tc', label: 'raises constitutional question', layer: 'de_jure' },
        { from: 'supremeCourt', to: 'tc', label: 'raises constitutional question', layer: 'de_jure' },
        { from: 'tc', to: 'parliament', label: 'strikes unconstitutional laws', layer: 'de_jure' },
        { from: 'tc', to: 'government', label: 'annuls unconstitutional acts/norms', layer: 'de_jure' },
        { from: 'tc', to: 'ccaa', label: 'adjudicates competence conflicts', layer: 'de_jure' },
      ],
      notes: ['Constitutional Court is outside ordinary judiciary and has exclusive constitutional jurisdiction.'],
      sources: [
        { title: 'Spanish Constitution (Title IX)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'Constitutional Court - Competences', url: 'https://www.tribunalconstitucional.es/en/tribunal/competencias/Paginas/default.aspx' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'election_representation',
      title: 'Election and Representation Diagram',
      purpose: 'How Spanish electoral rules convert votes into congressional and senatorial seats.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'provinces', label: 'Provinces as Districts', category: 'Subnational Government' },
        { id: 'parties', label: 'Party Lists', category: 'Political Party' },
        { id: 'congress', label: 'Congress of Deputies', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'junta', label: 'Central Electoral Board', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'voters', to: 'parties', label: 'votes for party lists', layer: 'de_jure' },
        { from: 'provinces', to: 'congress', label: 'allocate district seats', layer: 'de_jure' },
        { from: 'parties', to: 'congress', label: 'seats by D’Hondt', layer: 'de_jure' },
        { from: 'voters', to: 'senate', label: 'directly elects most senators', layer: 'de_jure' },
        { from: 'junta', to: 'congress', label: 'supervises and certifies', layer: 'de_jure' },
        { from: 'junta', to: 'senate', label: 'supervises and certifies', layer: 'de_jure' },
      ],
      notes: ['Provincial districting structurally favors larger statewide parties and concentrated regional parties.'],
      sources: [
        { title: 'Organic Law 5/1985 (LOREG)', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-1985-11672' },
        { title: 'Central Electoral Board', url: 'https://www.juntaelectoralcentral.es/cs/jec/home' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'territorial_federalism',
      title: 'Territorial and Autonomic State Diagram',
      purpose: 'Distribution of authority in Spain’s autonomic system and conflict-resolution channels.',
      level: 2,
      nodes: [
        { id: 'state', label: 'Central State', category: 'Executive Office' },
        { id: 'cortes', label: 'Cortes Generales', category: 'Legislature' },
        { id: 'ccaa', label: 'Autonomous Communities', category: 'Subnational Government' },
        { id: 'municipalities', label: 'Municipalities', category: 'Subnational Government' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'tc', label: 'Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'cortes', to: 'ccaa', label: 'defines framework competences', layer: 'de_jure' },
        { from: 'state', to: 'ccaa', label: 'coordination and shared powers', layer: 'de_jure' },
        { from: 'ccaa', to: 'municipalities', label: 'delegates implementation', layer: 'de_jure' },
        { from: 'tc', to: 'state', label: 'limits overreach in disputes', layer: 'de_jure' },
        { from: 'tc', to: 'ccaa', label: 'limits overreach in disputes', layer: 'de_jure' },
        { from: 'state', to: 'senate', label: 'invokes Art. 155 measures via approval', layer: 'de_jure' },
      ],
      notes: ['Spain is constitutionally unitary but highly decentralized in practice.'],
      sources: [
        { title: 'Spanish Constitution (Title VIII)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'Spanish Senate - Territorial Chamber', url: 'https://www.senado.es/web/conocersenado/index.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'budget_finance',
      title: 'Budget and Public Finance Diagram',
      purpose: 'Annual budget cycle from drafting and approval to execution and external audit.',
      level: 2,
      nodes: [
        { id: 'taxpayers', label: 'Taxpayers', category: 'Voters / Citizens' },
        { id: 'financeMin', label: 'Ministry of Finance', category: 'Ministry / Department' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'congress', label: 'Congress of Deputies', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'audit', label: 'Court of Auditors', category: 'Independent Agency' },
        { id: 'ccaa', label: 'Autonomous Communities', category: 'Subnational Government' },
      ],
      edges: [
        { from: 'taxpayers', to: 'financeMin', label: 'provide fiscal revenues', layer: 'de_jure' },
        { from: 'financeMin', to: 'government', label: 'prepares draft budget', layer: 'de_jure' },
        { from: 'government', to: 'congress', label: 'submits budget law', layer: 'de_jure' },
        { from: 'congress', to: 'senate', label: 'passes and transmits', layer: 'de_jure' },
        { from: 'senate', to: 'congress', label: 'amends and returns', layer: 'de_jure' },
        { from: 'government', to: 'ccaa', label: 'transfers financing and executes spending', layer: 'de_jure' },
        { from: 'audit', to: 'government', label: 'audits execution', layer: 'de_jure' },
      ],
      notes: ['If no new budget passes, prior appropriations are generally extended.'],
      sources: [
        { title: 'Spanish Constitution (Art. 134)', url: 'https://www.boe.es/legislacion/documentos/ConstitucionINGLES.pdf' },
        { title: 'General Budgetary Law 47/2003', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2003-21614' },
        { title: 'Court of Auditors (Tribunal de Cuentas)', url: 'https://www.tcu.es/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'de_facto_power',
      title: 'De Facto Power Map',
      purpose: 'Practical influence channels shaping outcomes beyond formal competences.',
      level: 2,
      nodes: [
        { id: 'partyLeaders', label: 'National Party Leadership', category: 'Political Party' },
        { id: 'pmOffice', label: 'Moncloa / PM Office', category: 'Executive Office' },
        { id: 'regionalParties', label: 'Regional/Nationalist Parties', category: 'Political Party' },
        { id: 'businessGroups', label: 'Business Associations', category: 'Independent Agency' },
        { id: 'tradeUnions', label: 'Trade Unions', category: 'Independent Agency' },
        { id: 'mediaPublic', label: 'Media and Public Opinion', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'partyLeaders', to: 'pmOffice', label: 'candidate control and discipline', layer: 'de_facto' },
        { from: 'regionalParties', to: 'pmOffice', label: 'investiture and legislative leverage', layer: 'de_facto' },
        { from: 'businessGroups', to: 'partyLeaders', label: 'economic policy lobbying', layer: 'de_facto' },
        { from: 'tradeUnions', to: 'pmOffice', label: 'social dialogue pressure', layer: 'de_facto' },
        { from: 'mediaPublic', to: 'partyLeaders', label: 'agenda and reputational pressure', layer: 'de_facto' },
      ],
      notes: ['Confidence: medium-high. Fragmentation increases bargaining power of pivotal blocs.'],
      sources: [
        { title: 'Congress of Deputies', url: 'https://www.congreso.es/en' },
        { title: 'Presidency of the Government (La Moncloa)', url: 'https://www.lamoncloa.gob.es/lang/en/Paginas/index.aspx' },
        { title: 'Bank of Spain - Institutional Role', url: 'https://www.bde.es/wbe/en/sobre-banco/' },
      ],
      lastUpdated: '2026-04-21',
    },
  ],
};
