import { portugalProfile, spainProfile } from '@/lib/political-system-profiles-pt-es';
export type PowerLayer = 'de_jure' | 'de_facto';

export interface PoliticalDiagramNode {
  id: string;
  label: string;
  category: string;
}

export interface PoliticalDiagramEdge {
  from: string;
  to: string;
  label: string;
  layer: PowerLayer;
}

export interface PoliticalDiagramSource {
  title: string;
  url: string;
}

export interface PoliticalDiagram {
  id:
    | 'master_system' | 'selection_appointment' | 'lawmaking'
    | 'government_formation'
    | 'oversight_removal'
    | 'judicial_review'
    | 'election_representation'
    | 'territorial_federalism'
    | 'budget_finance'
    | 'de_facto_power';
  title: string;
  purpose: string;
  level: 1 | 2 | 3;
  nodes: PoliticalDiagramNode[];
  edges: PoliticalDiagramEdge[];
  notes: string[];
  sources: PoliticalDiagramSource[];
  lastUpdated: string;
}

export interface CountryPoliticalProfile {
  countryCode: string;
  countryName: string; systemSummary: string;
  diagrams: PoliticalDiagram[];
}
const baseSources = {
  chFederalConstitution: {
    title: 'Switzerland - Federal Constitution',
    url: 'https://www.fedlex.admin.ch/eli/cc/1999/404/en',
  },
  chParliament: {
    title: 'Swiss Parliament - The Legislative Procedure',
    url: 'https://www.parlament.ch/en/%C3%BCber-das-parlament/how-parliament-works/the-legislative-procedure',
  },
  chGov: {
    title: 'The Federal Council Portal',
    url: 'https://www.admin.ch/gov/en/start.html',
  },
  ukGov: {
    title: 'UK Government and Parliament',
    url: 'https://www.gov.uk/government/how-government-works',
  },
  ukParliament: {
    title: 'UK Parliament - How laws are made',
    url: 'https://www.parliament.uk/about/how/laws/',
  },
  ukCommonsLibrary: {
    title: 'House of Commons Library - UK Constitution',
    url: 'https://commonslibrary.parliament.uk/research-briefings/cbp-8727/',
  },
  usConstitution: {
    title: 'Constitution of the United States',
    url: 'https://www.archives.gov/founding-docs/constitution-transcript',
  },
  usCongress: {
    title: 'US Congress - How Our Laws Are Made',
    url: 'https://www.congress.gov/resources/display/content/How+Our+Laws+Are+Made',
  },
  usScotus: {
    title: 'Supreme Court of the United States',
    url: 'https://www.supremecourt.gov/about/constitutional.aspx',
  },
  deGrundgesetz: {
    title: 'Basic Law for the Federal Republic of Germany',
    url: 'https://www.gesetze-im-internet.de/englisch_gg/',
  },
  deBundestag: {
    title: 'German Bundestag - Legislative Process',
    url: 'https://www.bundestag.de/en/parliament/function/legislation',
  },
  deBundesrat: {
    title: 'Bundesrat - Tasks and Function',
    url: 'https://www.bundesrat.de/EN/bundesrat-en/tasks/tasks-node.html',
  },
  frConstitution: {
    title: 'Constitution of the Fifth French Republic',
    url: 'https://www.conseil-constitutionnel.fr/en/constitution-of-4-october-1958',
  },
  frAssemblee: {
    title: 'French National Assembly - Lawmaking',
    url: 'https://www.assemblee-nationale.fr/dyn/en',
  },
  frSenat: {
    title: 'French Senate - Role',
    url: 'https://www.senat.fr/role/index.html',
  },
};
function buildMasterDiagram(
  summary: string,
  nodes: PoliticalDiagramNode[],
  edges: PoliticalDiagramEdge[],
  sources: PoliticalDiagramSource[],
): PoliticalDiagram {
  return {
    id: 'master_system',
    title: 'Master System Diagram',
    purpose: summary,
    level: 1,
    nodes,
    edges,
    notes: ['De jure relationships only in this view.'],
    sources,
    lastUpdated: '2026-04-21',
  };
}
const switzerlandProfile: CountryPoliticalProfile = {
  countryCode: 'CH',
  countryName: 'Switzerland',
  systemSummary: 'Federal direct-democratic republic with a collective executive and strong cantonal autonomy.',
  diagrams: [
    buildMasterDiagram(
      'High-level map of voters, federal legislature, collective executive, courts, and cantons.',
      [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'nr', label: 'National Council', category: 'Legislative Chamber' },
        { id: 'sr', label: 'Council of States', category: 'Legislative Chamber' },
        { id: 'federalAssembly', label: 'Federal Assembly', category: 'Legislature' },
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
        { id: 'federalCourt', label: 'Federal Supreme Court', category: 'Court' },
        { id: 'cantons', label: 'Cantons', category: 'Subnational Government' },
      ],
      [
        { from: 'voters', to: 'nr', label: 'elects', layer: 'de_jure' },
        { from: 'voters', to: 'sr', label: 'elects', layer: 'de_jure' },
        { from: 'federalAssembly', to: 'federalCouncil', label: 'elects', layer: 'de_jure' },
        { from: 'federalAssembly', to: 'federalCourt', label: 'elects judges', layer: 'de_jure' },
        { from: 'cantons', to: 'sr', label: 'territorial representation', layer: 'de_jure' },
        { from: 'federalCourt', to: 'federalCouncil', label: 'reviews administrative acts', layer: 'de_jure' },
      ],
      [baseSources.chFederalConstitution, baseSources.chParliament, baseSources.chGov],
    ),
    {
      id: 'selection_appointment',
      title: 'Selection and Appointment Diagram',
      purpose: 'Who selects national offices and top judicial actors.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'nr', label: 'National Council', category: 'Legislative Chamber' },
        { id: 'sr', label: 'Council of States', category: 'Legislative Chamber' },
        { id: 'federalAssembly', label: 'Federal Assembly', category: 'Legislature' },
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
        { id: 'federalCourt', label: 'Federal Supreme Court', category: 'Court' },
      ],
      edges: [
        { from: 'voters', to: 'nr', label: 'elects', layer: 'de_jure' },
        { from: 'voters', to: 'sr', label: 'elects', layer: 'de_jure' },
        { from: 'federalAssembly', to: 'federalCouncil', label: 'elects members', layer: 'de_jure' },
        { from: 'federalAssembly', to: 'federalCourt', label: 'elects judges', layer: 'de_jure' },
      ],
      notes: ['Federal Council presidency rotates annually among councillors.'],
      sources: [baseSources.chFederalConstitution, baseSources.chParliament],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'lawmaking',
      title: 'Lawmaking Diagram',
      purpose: 'How federal legislation and referendums interact.',
      level: 2,
      nodes: [
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
        { id: 'parliamentMembers', label: 'Parliament Members', category: 'Legislature' },
        { id: 'cantons', label: 'Cantons', category: 'Subnational Government' },
        { id: 'nr', label: 'National Council', category: 'Legislative Chamber' },
        { id: 'sr', label: 'Council of States', category: 'Legislative Chamber' },
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'federalCouncil', to: 'nr', label: 'introduces bill', layer: 'de_jure' },
        { from: 'parliamentMembers', to: 'nr', label: 'introduces bill', layer: 'de_jure' },
        { from: 'cantons', to: 'nr', label: 'cantonal initiative', layer: 'de_jure' },
        { from: 'nr', to: 'sr', label: 'passes and transmits', layer: 'de_jure' },
        { from: 'sr', to: 'nr', label: 'amends and returns', layer: 'de_jure' },
        { from: 'voters', to: 'nr', label: 'optional referendum can block', layer: 'de_jure' },
        { from: 'voters', to: 'sr', label: 'constitutional referendum decision', layer: 'de_jure' },
      ],
      notes: ['Constitutional amendments require double majority of people and cantons.'],
      sources: [baseSources.chFederalConstitution, baseSources.chParliament],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'government_formation',
      title: 'Government Formation Diagram',
      purpose: 'How Switzerland forms and stabilizes its collective executive.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'parties', label: 'Major Parties', category: 'Political Party' },
        { id: 'federalAssembly', label: 'Federal Assembly', category: 'Legislature' },
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
      ],
      edges: [
        { from: 'voters', to: 'federalAssembly', label: 'elects chambers', layer: 'de_jure' },
        { from: 'parties', to: 'federalAssembly', label: 'wins seats', layer: 'de_facto' },
        { from: 'federalAssembly', to: 'federalCouncil', label: 'elects councillors', layer: 'de_jure' },
        { from: 'parties', to: 'federalCouncil', label: 'concordance allocation influence', layer: 'de_facto' },
      ],
      notes: ['No parliamentary confidence vote mechanism like classic Westminster systems.'],
      sources: [baseSources.chFederalConstitution, baseSources.chGov],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'oversight_removal',
      title: 'Oversight and Removal Diagram',
      purpose: 'How federal actors monitor legality, spending, and executive conduct.',
      level: 2,
      nodes: [
        { id: 'federalAssembly', label: 'Federal Assembly', category: 'Legislature' },
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
        { id: 'audit', label: 'Swiss Federal Audit Office', category: 'Independent Agency' },
        { id: 'federalCourt', label: 'Federal Supreme Court', category: 'Court' },
      ],
      edges: [
        { from: 'federalAssembly', to: 'federalCouncil', label: 'oversight and questioning', layer: 'de_jure' },
        { from: 'audit', to: 'federalCouncil', label: 'audits spending', layer: 'de_jure' },
        { from: 'federalCourt', to: 'federalCouncil', label: 'reviews administrative acts', layer: 'de_jure' },
      ],
      notes: ['Federal councillors are not removable by parliamentary no-confidence during term.'],
      sources: [baseSources.chFederalConstitution, baseSources.chGov],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'judicial_review',
      title: 'Judicial and Constitutional Review Diagram',
      purpose: 'Court hierarchy and constitutional review limits at federal level.',
      level: 2,
      nodes: [
        { id: 'federalAssembly', label: 'Federal Assembly', category: 'Legislature' },
        { id: 'federalCourt', label: 'Federal Supreme Court', category: 'Court' },
        { id: 'cantonalCourts', label: 'Cantonal Courts', category: 'Court' },
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
      ],
      edges: [
        { from: 'federalAssembly', to: 'federalCourt', label: 'elects judges', layer: 'de_jure' },
        { from: 'cantonalCourts', to: 'federalCourt', label: 'appeals', layer: 'de_jure' },
        { from: 'federalCourt', to: 'federalCouncil', label: 'reviews executive acts', layer: 'de_jure' },
      ],
      notes: ['Federal statutes are generally binding on courts under Article 190 FC.'],
      sources: [baseSources.chFederalConstitution],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'election_representation',
      title: 'Election and Representation Diagram',
      purpose: 'How votes convert into seats and federal representation.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'parties', label: 'Parties and Lists', category: 'Political Party' },
        { id: 'nr', label: 'National Council', category: 'Legislative Chamber' },
        { id: 'sr', label: 'Council of States', category: 'Legislative Chamber' },
        { id: 'cantons', label: 'Cantons', category: 'Subnational Government' },
      ],
      edges: [
        { from: 'voters', to: 'parties', label: 'votes for lists/candidates', layer: 'de_jure' },
        { from: 'parties', to: 'nr', label: 'seats allocated proportionally', layer: 'de_jure' },
        { from: 'voters', to: 'sr', label: 'elects by cantonal rules', layer: 'de_jure' },
        { from: 'cantons', to: 'sr', label: 'sets electoral rules', layer: 'de_jure' },
      ],
      notes: ['National Council uses proportional representation in multi-member cantons.'],
      sources: [baseSources.chFederalConstitution, baseSources.chParliament],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'territorial_federalism',
      title: 'Territorial and Federalism Diagram',
      purpose: 'Division of authority between confederation, cantons, and communes.',
      level: 2,
      nodes: [
        { id: 'federalLevel', label: 'Confederation', category: 'Subnational Government' },
        { id: 'cantons', label: 'Cantons', category: 'Subnational Government' },
        { id: 'communes', label: 'Communes', category: 'Subnational Government' },
        { id: 'sr', label: 'Council of States', category: 'Legislative Chamber' },
        { id: 'federalCourt', label: 'Federal Supreme Court', category: 'Court' },
      ],
      edges: [
        { from: 'federalLevel', to: 'cantons', label: 'delegates/shared competences', layer: 'de_jure' },
        { from: 'cantons', to: 'communes', label: 'delegates local powers', layer: 'de_jure' },
        { from: 'cantons', to: 'sr', label: 'territorial representation', layer: 'de_jure' },
        { from: 'federalCourt', to: 'cantons', label: 'adjudicates federal-cantonal disputes', layer: 'de_jure' },
      ],
      notes: ['Residual powers remain with cantons unless assigned to confederation.'],
      sources: [baseSources.chFederalConstitution],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'budget_finance',
      title: 'Budget and Public Finance Diagram',
      purpose: 'How federal budget proposal, approval, and auditing works.',
      level: 2,
      nodes: [
        { id: 'taxpayers', label: 'Taxpayers', category: 'Voters / Citizens' },
        { id: 'fdf', label: 'Federal Department of Finance', category: 'Ministry / Department' },
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
        { id: 'federalAssembly', label: 'Federal Assembly', category: 'Legislature' },
        { id: 'cantons', label: 'Cantons', category: 'Subnational Government' },
        { id: 'audit', label: 'Swiss Federal Audit Office', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'taxpayers', to: 'fdf', label: 'funds through taxation', layer: 'de_jure' },
        { from: 'fdf', to: 'federalCouncil', label: 'drafts budget proposal', layer: 'de_jure' },
        { from: 'federalCouncil', to: 'federalAssembly', label: 'submits budget', layer: 'de_jure' },
        { from: 'federalAssembly', to: 'federalCouncil', label: 'approves/amends budget', layer: 'de_jure' },
        { from: 'federalCouncil', to: 'cantons', label: 'transfers federal funds', layer: 'de_jure' },
        { from: 'audit', to: 'federalCouncil', label: 'audits execution', layer: 'de_jure' },
      ],
      notes: ['Debt brake constrains federal budgeting over the cycle.'],
      sources: [baseSources.chFederalConstitution, baseSources.chGov],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'de_facto_power',
      title: 'De Facto Power Map',
      purpose: 'Practical influence map beyond formal constitutional text.',
      level: 2,
      nodes: [
        { id: 'majorParties', label: 'Major Parties', category: 'Political Party' },
        { id: 'federalCouncil', label: 'Federal Council', category: 'Executive Office' },
        { id: 'businessGroups', label: 'Business Associations', category: 'Independent Agency' },
        { id: 'tradeUnions', label: 'Trade Unions', category: 'Independent Agency' },
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'majorParties', to: 'federalCouncil', label: 'coalition discipline', layer: 'de_facto' },
        { from: 'businessGroups', to: 'majorParties', label: 'policy influence', layer: 'de_facto' },
        { from: 'tradeUnions', to: 'majorParties', label: 'policy bargaining', layer: 'de_facto' },
        { from: 'voters', to: 'majorParties', label: 'referendum pressure', layer: 'de_facto' },
      ],
      notes: ['Confidence: medium. Swiss consensus politics reduces winner-take-all dominance.'],
      sources: [baseSources.chGov, baseSources.chParliament],
      lastUpdated: '2026-04-21',
    },
  ],
};
const germanyProfile: CountryPoliticalProfile = {
  countryCode: 'DE',
  countryName: 'Germany',
  systemSummary: 'Federal parliamentary republic with chancellor government, bicameral federal legislature, and strong constitutional review.',
  diagrams: [
    buildMasterDiagram(
      'High-level map of Bundestag, Bundesrat, federal executive, constitutional court, and Länder.',
      [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'bundestag', label: 'Bundestag', category: 'Legislative Chamber' },
        { id: 'bundesrat', label: 'Bundesrat', category: 'Legislative Chamber' },
        { id: 'president', label: 'Federal President', category: 'Elected Office' },
        { id: 'chancellor', label: 'Federal Chancellor', category: 'Executive Office' },
        { id: 'cabinet', label: 'Federal Cabinet', category: 'Executive Office' },
        { id: 'court', label: 'Federal Constitutional Court', category: 'Court' },
        { id: 'lander', label: 'Länder', category: 'Subnational Government' },
      ],
      [
        { from: 'voters', to: 'bundestag', label: 'elects', layer: 'de_jure' },
        { from: 'lander', to: 'bundesrat', label: 'delegates governments', layer: 'de_jure' },
        { from: 'bundestag', to: 'chancellor', label: 'elects', layer: 'de_jure' },
        { from: 'president', to: 'chancellor', label: 'appoints', layer: 'de_jure' },
        { from: 'chancellor', to: 'cabinet', label: 'proposes ministers', layer: 'de_jure' },
        { from: 'president', to: 'cabinet', label: 'appoints ministers', layer: 'de_jure' },
        { from: 'court', to: 'bundestag', label: 'reviews constitutionality', layer: 'de_jure' },
      ],
      [baseSources.deGrundgesetz, baseSources.deBundestag, baseSources.deBundesrat],
    ),
    {
      id: 'selection_appointment',
      title: 'Selection and Appointment Diagram',
      purpose: 'Selection chains for chancellor, cabinet, president, and constitutional judges.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'bundestag', label: 'Bundestag', category: 'Legislative Chamber' },
        { id: 'bundesversammlung', label: 'Federal Convention', category: 'Legislature' },
        { id: 'president', label: 'Federal President', category: 'Elected Office' },
        { id: 'chancellor', label: 'Federal Chancellor', category: 'Executive Office' },
        { id: 'cabinet', label: 'Federal Ministers', category: 'Executive Office' },
        { id: 'court', label: 'Federal Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'voters', to: 'bundestag', label: 'elects', layer: 'de_jure' },
        { from: 'bundestag', to: 'chancellor', label: 'elects', layer: 'de_jure' },
        { from: 'president', to: 'chancellor', label: 'appoints', layer: 'de_jure' },
        { from: 'chancellor', to: 'cabinet', label: 'nominates', layer: 'de_jure' },
        { from: 'president', to: 'cabinet', label: 'appoints', layer: 'de_jure' },
        { from: 'bundesversammlung', to: 'president', label: 'elects', layer: 'de_jure' },
        { from: 'bundestag', to: 'court', label: 'elects half judges', layer: 'de_jure' },
      ],
      notes: ['Bundesrat elects the other half of constitutional judges.'],
      sources: [baseSources.deGrundgesetz, baseSources.deBundesrat],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'lawmaking',
      title: 'Lawmaking Diagram',
      purpose: 'Federal legislative path and veto points in bicameral process.',
      level: 2,
      nodes: [
        { id: 'federalGovernment', label: 'Federal Government', category: 'Executive Office' },
        { id: 'bundestag', label: 'Bundestag', category: 'Legislative Chamber' },
        { id: 'bundesrat', label: 'Bundesrat', category: 'Legislative Chamber' },
        { id: 'mediation', label: 'Mediation Committee', category: 'Independent Agency' },
        { id: 'president', label: 'Federal President', category: 'Elected Office' },
        { id: 'court', label: 'Federal Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'federalGovernment', to: 'bundestag', label: 'introduces bill', layer: 'de_jure' },
        { from: 'bundestag', to: 'bundesrat', label: 'passes and transmits', layer: 'de_jure' },
        { from: 'bundesrat', to: 'mediation', label: 'requests mediation', layer: 'de_jure' },
        { from: 'mediation', to: 'bundestag', label: 'proposes compromise', layer: 'de_jure' },
        { from: 'bundesrat', to: 'bundestag', label: 'consent/objection', layer: 'de_jure' },
        { from: 'president', to: 'bundestag', label: 'promulgates or refuses', layer: 'de_jure' },
        { from: 'court', to: 'bundestag', label: 'constitutional review', layer: 'de_jure' },
      ],
      notes: ['Consent bills require Bundesrat approval.'],
      sources: [baseSources.deGrundgesetz, baseSources.deBundestag, baseSources.deBundesrat],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'government_formation',
      title: 'Government Formation Diagram',
      purpose: 'How coalition bargaining and Bundestag procedure produce a Chancellor-led government.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'parties', label: 'Political Parties', category: 'Political Party' },
        { id: 'bundestag', label: 'Bundestag', category: 'Legislative Chamber' },
        { id: 'president', label: 'Federal President', category: 'Elected Office' },
        { id: 'chancellor', label: 'Federal Chancellor', category: 'Executive Office' },
        { id: 'cabinet', label: 'Federal Cabinet', category: 'Executive Office' },
      ],
      edges: [
        { from: 'voters', to: 'parties', label: 'allocates vote share', layer: 'de_facto' },
        { from: 'parties', to: 'bundestag', label: 'wins seats', layer: 'de_jure' },
        { from: 'parties', to: 'chancellor', label: 'coalition bargaining selects candidate', layer: 'de_facto' },
        { from: 'bundestag', to: 'chancellor', label: 'elects', layer: 'de_jure' },
        { from: 'president', to: 'chancellor', label: 'appoints elected candidate', layer: 'de_jure' },
        { from: 'chancellor', to: 'cabinet', label: 'selects ministers', layer: 'de_facto' },
        { from: 'president', to: 'cabinet', label: 'formally appoints ministers', layer: 'de_jure' },
      ],
      notes: ['Constructive no-confidence framework incentivizes stable coalition majorities.'],
      sources: [
        baseSources.deGrundgesetz,
        baseSources.deBundestag,
        { title: 'Federal Government - Structure and Tasks', url: 'https://www.bundesregierung.de/breg-en/federal-government' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'oversight_removal',
      title: 'Oversight and Removal Diagram',
      purpose: 'Parliamentary oversight, audit, and constitutional constraints on federal executive power.',
      level: 2,
      nodes: [
        { id: 'bundestag', label: 'Bundestag', category: 'Legislative Chamber' },
        { id: 'inquiry', label: 'Inquiry Committees', category: 'Legislature' },
        { id: 'chancellor', label: 'Federal Chancellor', category: 'Executive Office' },
        { id: 'ministers', label: 'Federal Ministers', category: 'Executive Office' },
        { id: 'audit', label: 'Federal Court of Auditors', category: 'Independent Agency' },
        { id: 'bverfg', label: 'Federal Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'bundestag', to: 'inquiry', label: 'creates investigations', layer: 'de_jure' },
        { from: 'inquiry', to: 'ministers', label: 'questions and compels evidence', layer: 'de_jure' },
        { from: 'bundestag', to: 'chancellor', label: 'constructive no-confidence', layer: 'de_jure' },
        { from: 'audit', to: 'bundestag', label: 'reports spending control', layer: 'de_jure' },
        { from: 'bverfg', to: 'chancellor', label: 'constitutional limits', layer: 'de_jure' },
        { from: 'bverfg', to: 'ministers', label: 'constitutional limits', layer: 'de_jure' },
      ],
      notes: ['Simple no-confidence removal is not available; replacement chancellor must be elected.'],
      sources: [
        baseSources.deGrundgesetz,
        baseSources.deBundestag,
        { title: 'Federal Court of Auditors (Bundesrechnungshof)', url: 'https://www.bundesrechnungshof.de/EN/Home/home_node.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'judicial_review',
      title: 'Judicial and Constitutional Review Diagram',
      purpose: 'Centralized constitutional review and referral paths in Germany.',
      level: 2,
      nodes: [
        { id: 'ordinaryCourts', label: 'Ordinary and Specialized Courts', category: 'Court' },
        { id: 'bverfg', label: 'Federal Constitutional Court', category: 'Court' },
        { id: 'bundestag', label: 'Bundestag', category: 'Legislature' },
        { id: 'bundesrat', label: 'Bundesrat', category: 'Legislative Chamber' },
        { id: 'federalGovernment', label: 'Federal Government', category: 'Executive Office' },
        { id: 'citizens', label: 'Individuals', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'ordinaryCourts', to: 'bverfg', label: 'refer constitutional questions', layer: 'de_jure' },
        { from: 'citizens', to: 'bverfg', label: 'constitutional complaint', layer: 'de_jure' },
        { from: 'bundestag', to: 'bverfg', label: 'constitutional application', layer: 'de_jure' },
        { from: 'bundesrat', to: 'bverfg', label: 'constitutional application', layer: 'de_jure' },
        { from: 'federalGovernment', to: 'bverfg', label: 'constitutional application', layer: 'de_jure' },
        { from: 'bverfg', to: 'bundestag', label: 'invalidates unconstitutional laws', layer: 'de_jure' },
        { from: 'bverfg', to: 'federalGovernment', label: 'binds executive action', layer: 'de_jure' },
      ],
      notes: ['Constitutional complaint is a key rights-protection pathway.'],
      sources: [
        baseSources.deGrundgesetz,
        { title: 'Federal Constitutional Court', url: 'https://www.bundesverfassungsgericht.de/EN/Homepage/homepage_node.html' },
        { title: 'Federal Constitutional Court Act (BVerfGG)', url: 'https://www.gesetze-im-internet.de/englisch_bverfgg/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'election_representation',
      title: 'Election and Representation Diagram',
      purpose: 'Mixed-member electoral design and Bundestag seat conversion.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'districtCandidates', label: 'District Candidates', category: 'Political Party' },
        { id: 'partyLists', label: 'Land Party Lists', category: 'Political Party' },
        { id: 'bundestag', label: 'Bundestag', category: 'Legislative Chamber' },
        { id: 'officer', label: 'Federal Returning Officer', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'voters', to: 'districtCandidates', label: 'first vote', layer: 'de_jure' },
        { from: 'voters', to: 'partyLists', label: 'second vote', layer: 'de_jure' },
        { from: 'districtCandidates', to: 'bundestag', label: 'direct mandates', layer: 'de_jure' },
        { from: 'partyLists', to: 'bundestag', label: 'proportional allocation', layer: 'de_jure' },
        { from: 'officer', to: 'bundestag', label: 'certifies seat distribution', layer: 'de_jure' },
      ],
      notes: ['Second vote drives proportional chamber composition.'],
      sources: [
        { title: 'Federal Election Act (BWahlG)', url: 'https://www.gesetze-im-internet.de/englisch_bwahlg/' },
        { title: 'Federal Returning Officer', url: 'https://www.bundeswahlleiterin.de/en/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'territorial_federalism',
      title: 'Territorial and Federalism Diagram',
      purpose: 'Cooperative federalism across federation, Länder, and local implementation.',
      level: 2,
      nodes: [
        { id: 'federation', label: 'Federation (Bund)', category: 'Subnational Government' },
        { id: 'bundesrat', label: 'Bundesrat', category: 'Legislative Chamber' },
        { id: 'lander', label: 'Länder', category: 'Subnational Government' },
        { id: 'municipalities', label: 'Municipalities', category: 'Subnational Government' },
        { id: 'bverfg', label: 'Federal Constitutional Court', category: 'Court' },
      ],
      edges: [
        { from: 'lander', to: 'bundesrat', label: 'send state-government delegates', layer: 'de_jure' },
        { from: 'federation', to: 'lander', label: 'enacts federal framework laws', layer: 'de_jure' },
        { from: 'lander', to: 'federation', label: 'execute many federal laws', layer: 'de_jure' },
        { from: 'lander', to: 'municipalities', label: 'delegate local authority', layer: 'de_jure' },
        { from: 'bverfg', to: 'federation', label: 'arbitrates competence disputes', layer: 'de_jure' },
        { from: 'bverfg', to: 'lander', label: 'arbitrates competence disputes', layer: 'de_jure' },
      ],
      notes: ['The Bundesrat is central to territorial representation in federal lawmaking.'],
      sources: [
        baseSources.deGrundgesetz,
        baseSources.deBundesrat,
        { title: 'Federal Ministry of the Interior - Federal Structure', url: 'https://www.bmi.bund.de/EN/topics/constitution/federal-structure/federal-structure-node.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'budget_finance',
      title: 'Budget and Public Finance Diagram',
      purpose: 'Federal budget drafting, parliamentary approval, and audit cycle.',
      level: 2,
      nodes: [
        { id: 'taxpayers', label: 'Taxpayers', category: 'Voters / Citizens' },
        { id: 'financeMinistry', label: 'Federal Ministry of Finance', category: 'Ministry / Department' },
        { id: 'federalGovernment', label: 'Federal Government', category: 'Executive Office' },
        { id: 'bundestag', label: 'Bundestag', category: 'Legislative Chamber' },
        { id: 'budgetCommittee', label: 'Budget Committee', category: 'Legislature' },
        { id: 'bundesrat', label: 'Bundesrat', category: 'Legislative Chamber' },
        { id: 'audit', label: 'Federal Court of Auditors', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'taxpayers', to: 'financeMinistry', label: 'revenue base', layer: 'de_jure' },
        { from: 'financeMinistry', to: 'federalGovernment', label: 'drafts budget', layer: 'de_jure' },
        { from: 'federalGovernment', to: 'bundestag', label: 'submits budget bill', layer: 'de_jure' },
        { from: 'bundestag', to: 'budgetCommittee', label: 'detailed scrutiny', layer: 'de_jure' },
        { from: 'budgetCommittee', to: 'bundestag', label: 'recommends appropriations', layer: 'de_jure' },
        { from: 'bundestag', to: 'bundesrat', label: 'passes budget legislation', layer: 'de_jure' },
        { from: 'audit', to: 'bundestag', label: 'audits execution and reports', layer: 'de_jure' },
      ],
      notes: ['Parliamentary budget sovereignty is a core constitutional principle.'],
      sources: [
        baseSources.deGrundgesetz,
        { title: 'Federal Ministry of Finance - Budget', url: 'https://www.bundesfinanzministerium.de/Web/EN/Issues/Budget/budget.html' },
        { title: 'Bundestag - Budget Committee', url: 'https://www.bundestag.de/en/committees/a08_budget' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'de_facto_power',
      title: 'De Facto Power Map',
      purpose: 'Practical influence channels through coalitions, Länder coordination, and societal bargaining.',
      level: 2,
      nodes: [
        { id: 'coalitionParties', label: 'Coalition Parties', category: 'Political Party' },
        { id: 'chancellery', label: 'Federal Chancellery', category: 'Executive Office' },
        { id: 'ministerPresidents', label: 'Conference of Minister-Presidents', category: 'Subnational Government' },
        { id: 'industry', label: 'Industry Associations', category: 'Independent Agency' },
        { id: 'unions', label: 'Trade Unions', category: 'Independent Agency' },
        { id: 'public', label: 'Media and Public Opinion', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'coalitionParties', to: 'chancellery', label: 'coalition discipline', layer: 'de_facto' },
        { from: 'ministerPresidents', to: 'chancellery', label: 'federal-state bargaining pressure', layer: 'de_facto' },
        { from: 'industry', to: 'coalitionParties', label: 'policy lobbying', layer: 'de_facto' },
        { from: 'unions', to: 'coalitionParties', label: 'social-partner influence', layer: 'de_facto' },
        { from: 'public', to: 'coalitionParties', label: 'electoral and reputational pressure', layer: 'de_facto' },
      ],
      notes: ['Confidence: medium. Coalition contracts and intergovernmental bargaining strongly shape outcomes.'],
      sources: [
        { title: 'Federal Chancellery', url: 'https://www.bundesregierung.de/breg-en/federal-government/federal-chancellery' },
        baseSources.deBundesrat,
        baseSources.deBundestag,
      ],
      lastUpdated: '2026-04-21',
    },
  ],
};
const ukProfile: CountryPoliticalProfile = {
  countryCode: 'GB',
  countryName: 'United Kingdom',
  systemSummary: 'Constitutional monarchy and parliamentary system centered on Commons confidence and cabinet government.',
  diagrams: [
    buildMasterDiagram(
      'High-level map of voters, parliament, crown, prime minister, and courts.',
      [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'commons', label: 'House of Commons', category: 'Legislative Chamber' },
        { id: 'lords', label: 'House of Lords', category: 'Legislative Chamber' },
        { id: 'monarch', label: 'Monarch', category: 'Monarchical / Religious Actor' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'cabinet', label: 'Cabinet', category: 'Executive Office' },
        { id: 'supremeCourt', label: 'UK Supreme Court', category: 'Court' },
        { id: 'devolved', label: 'Devolved Governments', category: 'Subnational Government' },
      ],
      [
        { from: 'voters', to: 'commons', label: 'elects', layer: 'de_jure' },
        { from: 'monarch', to: 'pm', label: 'appoints by convention', layer: 'de_jure' },
        { from: 'pm', to: 'cabinet', label: 'recommends ministers', layer: 'de_jure' },
        { from: 'monarch', to: 'cabinet', label: 'formally appoints', layer: 'de_jure' },
        { from: 'commons', to: 'pm', label: 'confidence/withdraws confidence', layer: 'de_jure' },
        { from: 'supremeCourt', to: 'pm', label: 'reviews legality', layer: 'de_jure' },
      ],
      [baseSources.ukGov, baseSources.ukParliament, baseSources.ukCommonsLibrary],
    ),
    {
      id: 'selection_appointment',
      title: 'Selection and Appointment Diagram',
      purpose: 'How the UK fills executive office, second chamber roles, and senior judges.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'commons', label: 'House of Commons', category: 'Legislative Chamber' },
        { id: 'monarch', label: 'Monarch', category: 'Monarchical / Religious Actor' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'cabinet', label: 'Cabinet Ministers', category: 'Executive Office' },
        { id: 'lords', label: 'House of Lords', category: 'Legislative Chamber' },
        { id: 'jsc', label: 'Judicial Appointments Bodies', category: 'Independent Agency' },
        { id: 'supremeCourt', label: 'UK Supreme Court', category: 'Court' },
      ],
      edges: [
        { from: 'voters', to: 'commons', label: 'elects MPs', layer: 'de_jure' },
        { from: 'commons', to: 'pm', label: 'confidence determines office-holder', layer: 'de_jure' },
        { from: 'monarch', to: 'pm', label: 'appoints PM by convention', layer: 'de_jure' },
        { from: 'pm', to: 'cabinet', label: 'selects ministers', layer: 'de_jure' },
        { from: 'monarch', to: 'cabinet', label: 'formally appoints ministers', layer: 'de_jure' },
        { from: 'pm', to: 'lords', label: 'advises life peer appointments', layer: 'de_jure' },
        { from: 'jsc', to: 'supremeCourt', label: 'recommends justices', layer: 'de_jure' },
        { from: 'pm', to: 'supremeCourt', label: 'advises Crown on appointment', layer: 'de_jure' },
      ],
      notes: ['Most executive appointments are legally Crown acts but politically controlled through Commons confidence and PM advice.'],
      sources: [
        { title: 'UK Government - How government works', url: 'https://www.gov.uk/government/how-government-works' },
        { title: 'UK Parliament - MPs and Lords', url: 'https://www.parliament.uk/about/mps-and-lords/' },
        { title: 'UK Supreme Court - Appointment of Justices', url: 'https://www.supremecourt.uk/about/appointments-of-justices.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'lawmaking',
      title: 'Lawmaking Diagram',
      purpose: 'How bills move through Westminster and become Acts.',
      level: 2,
      nodes: [
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'commons', label: 'House of Commons', category: 'Legislative Chamber' },
        { id: 'lords', label: 'House of Lords', category: 'Legislative Chamber' },
        { id: 'monarch', label: 'Monarch', category: 'Monarchical / Religious Actor' },
        { id: 'courts', label: 'Courts', category: 'Court' },
      ],
      edges: [
        { from: 'government', to: 'commons', label: 'introduces most bills', layer: 'de_jure' },
        { from: 'commons', to: 'lords', label: 'passes and transmits bill', layer: 'de_jure' },
        { from: 'lords', to: 'commons', label: 'amends/delays bill', layer: 'de_jure' },
        { from: 'commons', to: 'lords', label: 'can override delay (Parliament Acts route)', layer: 'de_jure' },
        { from: 'monarch', to: 'commons', label: 'royal assent completes enactment', layer: 'de_jure' },
        { from: 'courts', to: 'government', label: 'interpret and review delegated legislation', layer: 'de_jure' },
      ],
      notes: ['Royal assent is legally required but refusal is a dead convention in modern practice.'],
      sources: [baseSources.ukParliament, baseSources.ukCommonsLibrary],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'government_formation',
      title: 'Government Formation Diagram',
      purpose: 'How election results and Commons confidence produce a UK government.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'parties', label: 'Political Parties', category: 'Political Party' },
        { id: 'commons', label: 'House of Commons', category: 'Legislative Chamber' },
        { id: 'monarch', label: 'Monarch', category: 'Monarchical / Religious Actor' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'cabinet', label: 'Cabinet', category: 'Executive Office' },
      ],
      edges: [
        { from: 'voters', to: 'commons', label: 'elect MPs', layer: 'de_jure' },
        { from: 'voters', to: 'parties', label: 'vote distribution', layer: 'de_facto' },
        { from: 'parties', to: 'commons', label: 'convert seats into governing bloc', layer: 'de_facto' },
        { from: 'commons', to: 'pm', label: 'confidence identifies leader', layer: 'de_jure' },
        { from: 'monarch', to: 'pm', label: 'appoints confidence-capable leader', layer: 'de_jure' },
        { from: 'pm', to: 'cabinet', label: 'forms government', layer: 'de_jure' },
      ],
      notes: ['Caretaker conventions apply during transitions.'],
      sources: [
        { title: 'Cabinet Manual', url: 'https://www.gov.uk/government/publications/cabinet-manual' },
        baseSources.ukCommonsLibrary,
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'oversight_removal',
      title: 'Oversight and Removal Diagram',
      purpose: 'How Parliament and watchdogs scrutinize ministers and can force political exit.',
      level: 2,
      nodes: [
        { id: 'commons', label: 'House of Commons', category: 'Legislative Chamber' },
        { id: 'committees', label: 'Select Committees', category: 'Legislature' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'cabinet', label: 'Ministers', category: 'Executive Office' },
        { id: 'nao', label: 'National Audit Office', category: 'Independent Agency' },
        { id: 'courts', label: 'Courts', category: 'Court' },
      ],
      edges: [
        { from: 'commons', to: 'pm', label: 'confidence/no-confidence pressure', layer: 'de_jure' },
        { from: 'commons', to: 'cabinet', label: 'questions and censure', layer: 'de_jure' },
        { from: 'committees', to: 'cabinet', label: 'inquiries and hearings', layer: 'de_jure' },
        { from: 'nao', to: 'cabinet', label: 'audits spending', layer: 'de_jure' },
        { from: 'courts', to: 'pm', label: 'judicial review', layer: 'de_jure' },
        { from: 'pm', to: 'cabinet', label: 'dismisses ministers', layer: 'de_facto' },
      ],
      notes: ['Formal impeachment is obsolete; accountability is mainly parliamentary and judicial.'],
      sources: [
        { title: 'National Audit Office - About', url: 'https://www.nao.org.uk/about-us/' },
        baseSources.ukParliament,
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'judicial_review',
      title: 'Judicial and Constitutional Review Diagram',
      purpose: 'Legality review under parliamentary sovereignty and rights legislation.',
      level: 2,
      nodes: [
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'lowerCourts', label: 'Lower Courts and Tribunals', category: 'Court' },
        { id: 'supremeCourt', label: 'UK Supreme Court', category: 'Court' },
        { id: 'parliament', label: 'Parliament', category: 'Legislature' },
        { id: 'echr', label: 'European Court of Human Rights', category: 'Court' },
      ],
      edges: [
        { from: 'lowerCourts', to: 'government', label: 'judicial review of executive action', layer: 'de_jure' },
        { from: 'lowerCourts', to: 'supremeCourt', label: 'appeals', layer: 'de_jure' },
        { from: 'supremeCourt', to: 'government', label: 'final domestic legality rulings', layer: 'de_jure' },
        { from: 'supremeCourt', to: 'parliament', label: 'declaration of incompatibility (HRA)', layer: 'de_jure' },
        { from: 'echr', to: 'government', label: 'Convention violation judgments', layer: 'de_jure' },
      ],
      notes: ['Courts do not strike down primary Acts of Parliament.'],
      sources: [
        { title: 'Human Rights Act 1998', url: 'https://www.legislation.gov.uk/ukpga/1998/42/contents' },
        { title: 'UK Supreme Court - Constitutional role', url: 'https://www.supremecourt.uk/about/constitutional-role.html' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'election_representation',
      title: 'Election and Representation Diagram',
      purpose: 'How UK votes translate into Commons representation and governing advantage.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'constituencies', label: 'Single-Member Constituencies', category: 'Subnational Government' },
        { id: 'parties', label: 'Political Parties', category: 'Political Party' },
        { id: 'commons', label: 'House of Commons', category: 'Legislative Chamber' },
        { id: 'electoralCommission', label: 'Electoral Commission', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'voters', to: 'constituencies', label: 'cast local ballots', layer: 'de_jure' },
        { from: 'constituencies', to: 'commons', label: 'elect one MP by plurality', layer: 'de_jure' },
        { from: 'voters', to: 'parties', label: 'national vote distribution', layer: 'de_facto' },
        { from: 'parties', to: 'commons', label: 'seat bonus from FPTP geography', layer: 'de_facto' },
        { from: 'electoralCommission', to: 'parties', label: 'regulates finance/reporting', layer: 'de_jure' },
      ],
      notes: ['Commons uses first-past-the-post.'],
      sources: [
        { title: 'Electoral Commission - Voting and elections', url: 'https://www.electoralcommission.org.uk/i-am-a/voter' },
        baseSources.ukParliament,
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'territorial_federalism',
      title: 'Territorial and Devolution Diagram',
      purpose: 'Distribution of authority in a devolved but unitary UK constitutional order.',
      level: 2,
      nodes: [
        { id: 'ukParliament', label: 'UK Parliament', category: 'Legislature' },
        { id: 'ukGovernment', label: 'UK Government', category: 'Executive Office' },
        { id: 'scotland', label: 'Scottish Institutions', category: 'Subnational Government' },
        { id: 'wales', label: 'Welsh Institutions', category: 'Subnational Government' },
        { id: 'ni', label: 'Northern Ireland Institutions', category: 'Subnational Government' },
        { id: 'supremeCourt', label: 'UK Supreme Court', category: 'Court' },
      ],
      edges: [
        { from: 'ukParliament', to: 'scotland', label: 'sets devolved competence', layer: 'de_jure' },
        { from: 'ukParliament', to: 'wales', label: 'sets devolved competence', layer: 'de_jure' },
        { from: 'ukParliament', to: 'ni', label: 'sets devolved competence', layer: 'de_jure' },
        { from: 'ukGovernment', to: 'scotland', label: 'retains reserved powers', layer: 'de_jure' },
        { from: 'ukGovernment', to: 'wales', label: 'retains reserved powers', layer: 'de_jure' },
        { from: 'supremeCourt', to: 'scotland', label: 'rules on competence disputes', layer: 'de_jure' },
        { from: 'supremeCourt', to: 'wales', label: 'rules on competence disputes', layer: 'de_jure' },
        { from: 'supremeCourt', to: 'ni', label: 'rules on competence disputes', layer: 'de_jure' },
      ],
      notes: ['Sewel is a political convention rather than a legally enforceable limit.'],
      sources: [
        { title: 'Scotland Act 1998', url: 'https://www.legislation.gov.uk/ukpga/1998/46/contents' },
        { title: 'Government of Wales Act 2006', url: 'https://www.legislation.gov.uk/ukpga/2006/32/contents' },
        { title: 'Northern Ireland Act 1998', url: 'https://www.legislation.gov.uk/ukpga/1998/47/contents' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'budget_finance',
      title: 'Budget and Public Finance Diagram',
      purpose: 'UK fiscal drafting, authorization, execution, and audit.',
      level: 2,
      nodes: [
        { id: 'taxpayers', label: 'Taxpayers', category: 'Voters / Citizens' },
        { id: 'treasury', label: 'HM Treasury', category: 'Ministry / Department' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'commons', label: 'House of Commons', category: 'Legislative Chamber' },
        { id: 'lords', label: 'House of Lords', category: 'Legislative Chamber' },
        { id: 'obr', label: 'Office for Budget Responsibility', category: 'Independent Agency' },
        { id: 'nao', label: 'National Audit Office', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'taxpayers', to: 'treasury', label: 'fund revenues', layer: 'de_jure' },
        { from: 'treasury', to: 'government', label: 'prepares budget', layer: 'de_jure' },
        { from: 'government', to: 'commons', label: 'submits finance and supply', layer: 'de_jure' },
        { from: 'commons', to: 'government', label: 'grants supply and taxation authority', layer: 'de_jure' },
        { from: 'lords', to: 'commons', label: 'limited delay on money bills', layer: 'de_jure' },
        { from: 'obr', to: 'government', label: 'fiscal forecast and scrutiny', layer: 'de_jure' },
        { from: 'nao', to: 'government', label: 'audits expenditure outcomes', layer: 'de_jure' },
      ],
      notes: ['Commons financial privilege is decisive in budget politics.'],
      sources: [
        { title: 'HM Treasury', url: 'https://www.gov.uk/government/organisations/hm-treasury' },
        { title: 'Office for Budget Responsibility', url: 'https://obr.uk/about-the-obr/' },
        { title: 'National Audit Office', url: 'https://www.nao.org.uk/about-us/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'de_facto_power',
      title: 'De Facto Power Map',
      purpose: 'Practical influence structure around party control, PM office, and agenda-setters.',
      level: 2,
      nodes: [
        { id: 'pm', label: 'Prime Minister and No.10', category: 'Executive Office' },
        { id: 'cabinet', label: 'Cabinet', category: 'Executive Office' },
        { id: 'whips', label: 'Party Whips', category: 'Political Party' },
        { id: 'media', label: 'National Media', category: 'Independent Agency' },
        { id: 'civilService', label: 'Senior Civil Service', category: 'Independent Agency' },
        { id: 'backbenchers', label: 'Backbench MPs', category: 'Legislature' },
      ],
      edges: [
        { from: 'whips', to: 'backbenchers', label: 'vote discipline and career pressure', layer: 'de_facto' },
        { from: 'pm', to: 'cabinet', label: 'agenda control and portfolios', layer: 'de_facto' },
        { from: 'civilService', to: 'pm', label: 'implementation leverage', layer: 'de_facto' },
        { from: 'media', to: 'pm', label: 'narrative pressure', layer: 'de_facto' },
        { from: 'backbenchers', to: 'pm', label: 'rebellion risk', layer: 'de_facto' },
      ],
      notes: ['Confidence: medium-high. Party management often defines governing bandwidth.'],
      sources: [
        { title: 'Institute for Government - Ministers', url: 'https://www.instituteforgovernment.org.uk/explainer/ministers' },
        baseSources.ukCommonsLibrary,
      ],
      lastUpdated: '2026-04-21',
    },
  ],
};
const usProfile: CountryPoliticalProfile = {
  countryCode: 'US',
  countryName: 'United States',
  systemSummary: 'Federal presidential republic with separated powers, bicameral legislature, and strong judicial review.',
  diagrams: [
    buildMasterDiagram(
      'High-level map of voters, president, congress, supreme court, and states.',
      [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'house', label: 'House of Representatives', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'congress', label: 'Congress', category: 'Legislature' },
        { id: 'cabinet', label: 'Cabinet', category: 'Executive Office' },
        { id: 'scotus', label: 'Supreme Court', category: 'Court' },
        { id: 'states', label: 'States', category: 'Subnational Government' },
      ],
      [
        { from: 'voters', to: 'president', label: 'elects (Electoral College path)', layer: 'de_jure' },
        { from: 'voters', to: 'house', label: 'elects', layer: 'de_jure' },
        { from: 'states', to: 'senate', label: 'elects senators', layer: 'de_jure' },
        { from: 'president', to: 'cabinet', label: 'nominates', layer: 'de_jure' },
        { from: 'senate', to: 'cabinet', label: 'confirms', layer: 'de_jure' },
        { from: 'president', to: 'congress', label: 'vetoes bills', layer: 'de_jure' },
        { from: 'congress', to: 'president', label: 'overrides veto / impeaches', layer: 'de_jure' },
        { from: 'scotus', to: 'congress', label: 'judicial review', layer: 'de_jure' },
        { from: 'scotus', to: 'president', label: 'judicial review', layer: 'de_jure' },
      ],
      [baseSources.usConstitution, baseSources.usCongress, baseSources.usScotus],
    ),
    {
      id: 'selection_appointment',
      title: 'Selection and Appointment Diagram',
      purpose: 'Electoral and appointment pathways for executive, legislative, and judicial offices.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'electoralCollege', label: 'Electoral College', category: 'Legislature' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'house', label: 'House of Representatives', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'cabinet', label: 'Cabinet Officers', category: 'Executive Office' },
        { id: 'federalJudges', label: 'Federal Judges', category: 'Court' },
      ],
      edges: [
        { from: 'voters', to: 'house', label: 'elects representatives', layer: 'de_jure' },
        { from: 'voters', to: 'senate', label: 'elects senators', layer: 'de_jure' },
        { from: 'voters', to: 'electoralCollege', label: 'chooses electors by state vote', layer: 'de_jure' },
        { from: 'electoralCollege', to: 'president', label: 'elects president', layer: 'de_jure' },
        { from: 'president', to: 'cabinet', label: 'nominates', layer: 'de_jure' },
        { from: 'senate', to: 'cabinet', label: 'advice and consent', layer: 'de_jure' },
        { from: 'president', to: 'federalJudges', label: 'nominates', layer: 'de_jure' },
        { from: 'senate', to: 'federalJudges', label: 'confirms', layer: 'de_jure' },
      ],
      notes: ['States administer elections while Congress certifies electoral vote counting under statute.'],
      sources: [
        baseSources.usConstitution,
        { title: 'National Archives - Electoral College', url: 'https://www.archives.gov/electoral-college' },
        { title: 'U.S. Senate - Nominations', url: 'https://www.senate.gov/legislative/nominations.htm' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'lawmaking',
      title: 'Lawmaking Diagram',
      purpose: 'Federal bill-to-law process and major veto/override checkpoints.',
      level: 2,
      nodes: [
        { id: 'house', label: 'House of Representatives', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'conference', label: 'Conference Committee', category: 'Legislature' },
        { id: 'congress', label: 'Congress', category: 'Legislature' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'scotus', label: 'Supreme Court', category: 'Court' },
      ],
      edges: [
        { from: 'house', to: 'senate', label: 'passes and transmits bill', layer: 'de_jure' },
        { from: 'senate', to: 'house', label: 'passes and transmits bill', layer: 'de_jure' },
        { from: 'house', to: 'conference', label: 'resolves bicameral differences', layer: 'de_jure' },
        { from: 'senate', to: 'conference', label: 'resolves bicameral differences', layer: 'de_jure' },
        { from: 'conference', to: 'congress', label: 'returns unified text', layer: 'de_jure' },
        { from: 'congress', to: 'president', label: 'presents enrolled bill', layer: 'de_jure' },
        { from: 'president', to: 'congress', label: 'signs or vetoes', layer: 'de_jure' },
        { from: 'congress', to: 'president', label: 'can override veto (2/3 both chambers)', layer: 'de_jure' },
        { from: 'scotus', to: 'congress', label: 'judicial review of statutes', layer: 'de_jure' },
      ],
      notes: ['Revenue bills originate in the House; Senate amends.'],
      sources: [baseSources.usConstitution, baseSources.usCongress],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'government_formation',
      title: 'Government Formation Diagram',
      purpose: 'Presidential transition, executive staffing, and Senate-confirmed government build-out.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'electoralCollege', label: 'Electoral College', category: 'Legislature' },
        { id: 'presidentElect', label: 'President-Elect', category: 'Executive Office' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'cabinet', label: 'Cabinet Secretaries', category: 'Executive Office' },
        { id: 'agencies', label: 'Federal Agencies', category: 'Ministry / Department' },
      ],
      edges: [
        { from: 'voters', to: 'electoralCollege', label: 'state-level presidential vote', layer: 'de_jure' },
        { from: 'electoralCollege', to: 'presidentElect', label: 'determines winner', layer: 'de_jure' },
        { from: 'presidentElect', to: 'president', label: 'inauguration transfer', layer: 'de_jure' },
        { from: 'president', to: 'cabinet', label: 'nominates principal officers', layer: 'de_jure' },
        { from: 'senate', to: 'cabinet', label: 'confirms nominees', layer: 'de_jure' },
        { from: 'cabinet', to: 'agencies', label: 'heads departments', layer: 'de_jure' },
      ],
      notes: ['Executive formation does not depend on legislative confidence votes.'],
      sources: [
        baseSources.usConstitution,
        { title: 'GSA - Presidential Transition', url: 'https://www.gsa.gov/governmentwide-initiatives/presidential-transition-directory' },
        { title: 'White House - Executive Branch', url: 'https://www.whitehouse.gov/about-the-white-house/our-government/the-executive-branch/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'oversight_removal',
      title: 'Oversight and Removal Diagram',
      purpose: 'Congressional oversight and impeachment/removal routes for federal officials.',
      level: 2,
      nodes: [
        { id: 'house', label: 'House of Representatives', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'committees', label: 'Congressional Committees', category: 'Legislature' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'agencies', label: 'Executive Agencies', category: 'Ministry / Department' },
        { id: 'gao', label: 'Government Accountability Office', category: 'Independent Agency' },
        { id: 'courts', label: 'Federal Courts', category: 'Court' },
      ],
      edges: [
        { from: 'house', to: 'committees', label: 'delegates oversight investigations', layer: 'de_jure' },
        { from: 'senate', to: 'committees', label: 'delegates oversight investigations', layer: 'de_jure' },
        { from: 'committees', to: 'agencies', label: 'hearings and subpoenas', layer: 'de_jure' },
        { from: 'gao', to: 'committees', label: 'audit and evaluation reports', layer: 'de_jure' },
        { from: 'house', to: 'president', label: 'impeaches by majority', layer: 'de_jure' },
        { from: 'senate', to: 'president', label: 'tries and removes on 2/3 conviction', layer: 'de_jure' },
        { from: 'courts', to: 'committees', label: 'resolve subpoena disputes', layer: 'de_jure' },
      ],
      notes: ['Impeachment removal is rare and requires supermajority in the Senate.'],
      sources: [
        baseSources.usConstitution,
        { title: 'GAO - About', url: 'https://www.gao.gov/about' },
        { title: 'U.S. House - Impeachment resources', url: 'https://www.house.gov/the-house-explained' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'judicial_review',
      title: 'Judicial and Constitutional Review Diagram',
      purpose: 'Federal judicial hierarchy and constitutional review of statutes and executive action.',
      level: 2,
      nodes: [
        { id: 'districtCourts', label: 'U.S. District Courts', category: 'Court' },
        { id: 'appealsCourts', label: 'U.S. Courts of Appeals', category: 'Court' },
        { id: 'scotus', label: 'Supreme Court', category: 'Court' },
        { id: 'congress', label: 'Congress', category: 'Legislature' },
        { id: 'president', label: 'President/Executive Branch', category: 'Executive Office' },
        { id: 'states', label: 'States', category: 'Subnational Government' },
      ],
      edges: [
        { from: 'districtCourts', to: 'appealsCourts', label: 'appeals', layer: 'de_jure' },
        { from: 'appealsCourts', to: 'scotus', label: 'certiorari petitions', layer: 'de_jure' },
        { from: 'scotus', to: 'congress', label: 'invalidates unconstitutional statutes', layer: 'de_jure' },
        { from: 'scotus', to: 'president', label: 'reviews executive action', layer: 'de_jure' },
        { from: 'scotus', to: 'states', label: 'reviews state law under federal Constitution', layer: 'de_jure' },
      ],
      notes: ['Judicial review doctrine is rooted in Marbury v. Madison and later practice.'],
      sources: [baseSources.usScotus, baseSources.usConstitution],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'election_representation',
      title: 'Election and Representation Diagram',
      purpose: 'How federal elections convert votes into House, Senate, and presidential authority.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'stateAuthorities', label: 'State Election Authorities', category: 'Subnational Government' },
        { id: 'house', label: 'House of Representatives', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'electoralCollege', label: 'Electoral College', category: 'Legislature' },
        { id: 'president', label: 'President', category: 'Executive Office' },
      ],
      edges: [
        { from: 'voters', to: 'house', label: 'district plurality elections', layer: 'de_jure' },
        { from: 'voters', to: 'senate', label: 'statewide elections', layer: 'de_jure' },
        { from: 'voters', to: 'stateAuthorities', label: 'cast ballots', layer: 'de_jure' },
        { from: 'stateAuthorities', to: 'electoralCollege', label: 'certify electors', layer: 'de_jure' },
        { from: 'electoralCollege', to: 'president', label: 'casts decisive votes', layer: 'de_jure' },
      ],
      notes: ['Election administration is decentralized and state-led.'],
      sources: [
        { title: 'Election Assistance Commission', url: 'https://www.eac.gov/' },
        { title: 'National Archives - Electoral College', url: 'https://www.archives.gov/electoral-college' },
        baseSources.usConstitution,
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'territorial_federalism',
      title: 'Territorial and Federalism Diagram',
      purpose: 'Federal-state power distribution, cooperative implementation, and constitutional dispute routes.',
      level: 2,
      nodes: [
        { id: 'federal', label: 'Federal Government', category: 'Subnational Government' },
        { id: 'congress', label: 'Congress', category: 'Legislature' },
        { id: 'states', label: 'States', category: 'Subnational Government' },
        { id: 'locals', label: 'Local Governments', category: 'Subnational Government' },
        { id: 'agencies', label: 'Federal Agencies', category: 'Ministry / Department' },
        { id: 'scotus', label: 'Supreme Court', category: 'Court' },
      ],
      edges: [
        { from: 'congress', to: 'states', label: 'preemption and conditional spending', layer: 'de_jure' },
        { from: 'federal', to: 'agencies', label: 'implements national programs', layer: 'de_jure' },
        { from: 'agencies', to: 'states', label: 'cooperative federalism grants/regulation', layer: 'de_jure' },
        { from: 'states', to: 'locals', label: 'delegate local powers', layer: 'de_jure' },
        { from: 'states', to: 'federal', label: 'retain reserved powers', layer: 'de_jure' },
        { from: 'scotus', to: 'congress', label: 'polices enumerated-power limits', layer: 'de_jure' },
        { from: 'scotus', to: 'states', label: 'adjudicates federal-state disputes', layer: 'de_jure' },
      ],
      notes: ['Local governments are primarily creatures of state law.'],
      sources: [baseSources.usConstitution, baseSources.usScotus],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'budget_finance',
      title: 'Budget and Public Finance Diagram',
      purpose: 'Federal budget formulation, appropriations, execution, borrowing, and audit oversight.',
      level: 2,
      nodes: [
        { id: 'omb', label: 'Office of Management and Budget', category: 'Ministry / Department' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'congress', label: 'Congress', category: 'Legislature' },
        { id: 'treasury', label: 'U.S. Treasury', category: 'Ministry / Department' },
        { id: 'agencies', label: 'Federal Agencies', category: 'Ministry / Department' },
        { id: 'gao', label: 'Government Accountability Office', category: 'Independent Agency' },
        { id: 'taxpayers', label: 'Taxpayers', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'omb', to: 'president', label: 'prepares budget request', layer: 'de_jure' },
        { from: 'president', to: 'congress', label: 'submits annual budget', layer: 'de_jure' },
        { from: 'congress', to: 'agencies', label: 'enacts appropriations', layer: 'de_jure' },
        { from: 'taxpayers', to: 'treasury', label: 'tax revenues', layer: 'de_jure' },
        { from: 'treasury', to: 'agencies', label: 'disburses funds', layer: 'de_jure' },
        { from: 'treasury', to: 'congress', label: 'debt issuance under statute', layer: 'de_jure' },
        { from: 'gao', to: 'congress', label: 'audits and oversight reports', layer: 'de_jure' },
      ],
      notes: ['Congress controls appropriations; executive controls proposal and execution within statute.'],
      sources: [
        { title: 'Office of Management and Budget', url: 'https://www.whitehouse.gov/omb/' },
        { title: 'U.S. Treasury - Financing the government', url: 'https://home.treasury.gov/policy-issues/financing-the-government' },
        { title: 'GAO', url: 'https://www.gao.gov/' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'de_facto_power',
      title: 'De Facto Power Map',
      purpose: 'Practical influence centers shaping federal agenda beyond formal separation of powers.',
      level: 2,
      nodes: [
        { id: 'partyLeadership', label: 'Party Leadership in Congress', category: 'Political Party' },
        { id: 'whiteHouseStaff', label: 'White House Senior Staff', category: 'Executive Office' },
        { id: 'committeeChairs', label: 'Committee Chairs', category: 'Legislature' },
        { id: 'interestGroups', label: 'Interest Groups', category: 'Independent Agency' },
        { id: 'donors', label: 'Major Donors/PACs', category: 'Independent Agency' },
        { id: 'media', label: 'Media and Platforms', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'partyLeadership', to: 'committeeChairs', label: 'agenda and floor control', layer: 'de_facto' },
        { from: 'whiteHouseStaff', to: 'partyLeadership', label: 'strategy coordination', layer: 'de_facto' },
        { from: 'interestGroups', to: 'committeeChairs', label: 'drafting influence', layer: 'de_facto' },
        { from: 'donors', to: 'partyLeadership', label: 'campaign finance leverage', layer: 'de_facto' },
        { from: 'media', to: 'partyLeadership', label: 'base mobilization pressure', layer: 'de_facto' },
      ],
      notes: ['Confidence: medium. Committee gatekeeping and party leadership power remain decisive.'],
      sources: [
        { title: 'Federal Election Commission', url: 'https://www.fec.gov/' },
        { title: 'Senate Lobbying Disclosure Database', url: 'https://lda.senate.gov/' },
        { title: 'CRS Reports', url: 'https://crsreports.congress.gov/' },
      ],
      lastUpdated: '2026-04-21',
    },
  ],
};
const franceProfile: CountryPoliticalProfile = {
  countryCode: 'FR',
  countryName: 'France',
  systemSummary: 'Unitary semi-presidential republic balancing a directly elected president with a confidence-dependent government.',
  diagrams: [
    buildMasterDiagram(
      'High-level map of president, parliament, government, constitutional council, and territorial collectivities.',
      [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'assemblee', label: 'National Assembly', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'cc', label: 'Constitutional Council', category: 'Court' },
        { id: 'regions', label: 'Regions and Communes', category: 'Subnational Government' },
      ],
      [
        { from: 'voters', to: 'president', label: 'elects', layer: 'de_jure' },
        { from: 'voters', to: 'assemblee', label: 'elects', layer: 'de_jure' },
        { from: 'president', to: 'pm', label: 'appoints', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'proposes ministers', layer: 'de_jure' },
        { from: 'president', to: 'government', label: 'appoints ministers', layer: 'de_jure' },
        { from: 'assemblee', to: 'government', label: 'can remove by no-confidence', layer: 'de_jure' },
        { from: 'cc', to: 'assemblee', label: 'constitutional review', layer: 'de_jure' },
      ],
      [baseSources.frConstitution, baseSources.frAssemblee, baseSources.frSenat],
    ),
    {
      id: 'selection_appointment',
      title: 'Selection and Appointment Diagram',
      purpose: 'How France selects president, appoints government, and composes constitutional review bodies.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'government', label: 'Government Ministers', category: 'Executive Office' },
        { id: 'assemblee', label: 'National Assembly', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'cc', label: 'Constitutional Council', category: 'Court' },
      ],
      edges: [
        { from: 'voters', to: 'president', label: 'elects directly', layer: 'de_jure' },
        { from: 'president', to: 'pm', label: 'appoints Prime Minister', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'proposes ministers', layer: 'de_jure' },
        { from: 'president', to: 'government', label: 'appoints ministers', layer: 'de_jure' },
        { from: 'assemblee', to: 'pm', label: 'confidence constraint on tenure', layer: 'de_jure' },
        { from: 'president', to: 'cc', label: 'appoints 3 members', layer: 'de_jure' },
        { from: 'assemblee', to: 'cc', label: 'assembly president appoints 3 members', layer: 'de_jure' },
        { from: 'senate', to: 'cc', label: 'senate president appoints 3 members', layer: 'de_jure' },
      ],
      notes: ['Parliamentary majority determines whether government can survive censure.'],
      sources: [baseSources.frConstitution, baseSources.frAssemblee, baseSources.frSenat],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'lawmaking',
      title: 'Lawmaking Diagram',
      purpose: 'How ordinary legislation moves through both chambers and promulgation.',
      level: 2,
      nodes: [
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'assemblee', label: 'National Assembly', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'cmp', label: 'Joint Committee (CMP)', category: 'Legislature' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'cc', label: 'Constitutional Council', category: 'Court' },
      ],
      edges: [
        { from: 'government', to: 'assemblee', label: 'submits bill', layer: 'de_jure' },
        { from: 'assemblee', to: 'senate', label: 'passes/transmits', layer: 'de_jure' },
        { from: 'senate', to: 'assemblee', label: 'amends/returns', layer: 'de_jure' },
        { from: 'assemblee', to: 'cmp', label: 'seeks compromise', layer: 'de_jure' },
        { from: 'senate', to: 'cmp', label: 'seeks compromise', layer: 'de_jure' },
        { from: 'assemblee', to: 'senate', label: 'can have final say', layer: 'de_jure' },
        { from: 'president', to: 'assemblee', label: 'promulgates enacted law', layer: 'de_jure' },
        { from: 'cc', to: 'assemblee', label: 'a priori constitutional review', layer: 'de_jure' },
      ],
      notes: ['Government agenda tools can accelerate adoption of priority texts.'],
      sources: [baseSources.frConstitution, baseSources.frAssemblee, baseSources.frSenat],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'government_formation',
      title: 'Government Formation Diagram',
      purpose: 'How presidential election, assembly arithmetic, and cohabitation shape government.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'parties', label: 'Parties and Blocs', category: 'Political Party' },
        { id: 'assemblee', label: 'National Assembly', category: 'Legislative Chamber' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
      ],
      edges: [
        { from: 'voters', to: 'president', label: 'elect president', layer: 'de_jure' },
        { from: 'voters', to: 'assemblee', label: 'elect deputies', layer: 'de_jure' },
        { from: 'parties', to: 'assemblee', label: 'form governing or blocking blocs', layer: 'de_facto' },
        { from: 'president', to: 'pm', label: 'appoints PM', layer: 'de_jure' },
        { from: 'assemblee', to: 'government', label: 'can censure and force resignation', layer: 'de_jure' },
        { from: 'pm', to: 'government', label: 'organizes cabinet action', layer: 'de_jure' },
      ],
      notes: ['Cohabitation shifts day-to-day policy leadership toward PM/cabinet.'],
      sources: [baseSources.frConstitution, baseSources.frAssemblee],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'oversight_removal',
      title: 'Oversight and Removal Diagram',
      purpose: 'Parliamentary scrutiny, audit institutions, and constitutional constraints on executive action.',
      level: 2,
      nodes: [
        { id: 'assemblee', label: 'National Assembly', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'pm', label: 'Prime Minister', category: 'Executive Office' },
        { id: 'courDesComptes', label: 'Cour des comptes', category: 'Independent Agency' },
        { id: 'cc', label: 'Constitutional Council', category: 'Court' },
      ],
      edges: [
        { from: 'assemblee', to: 'government', label: 'censure motion', layer: 'de_jure' },
        { from: 'assemblee', to: 'pm', label: 'questions and hearings', layer: 'de_jure' },
        { from: 'senate', to: 'government', label: 'inquiries and scrutiny', layer: 'de_jure' },
        { from: 'courDesComptes', to: 'government', label: 'audits spending', layer: 'de_jure' },
        { from: 'cc', to: 'government', label: 'annuls unconstitutional provisions', layer: 'de_jure' },
      ],
      notes: ['Executive accountability is strong in parliament but shaped by majority discipline.'],
      sources: [
        baseSources.frConstitution,
        { title: 'Cour des comptes', url: 'https://www.ccomptes.fr/en' },
        baseSources.frAssemblee,
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'judicial_review',
      title: 'Judicial and Constitutional Review Diagram',
      purpose: 'Split between constitutional review and administrative legality review.',
      level: 2,
      nodes: [
        { id: 'cc', label: 'Constitutional Council', category: 'Court' },
        { id: 'conseilEtat', label: 'Conseil d’État', category: 'Court' },
        { id: 'courCass', label: 'Court of Cassation', category: 'Court' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'parliament', label: 'Parliament', category: 'Legislature' },
      ],
      edges: [
        { from: 'conseilEtat', to: 'government', label: 'annuls unlawful executive acts', layer: 'de_jure' },
        { from: 'courCass', to: 'cc', label: 'refers QPC', layer: 'de_jure' },
        { from: 'conseilEtat', to: 'cc', label: 'refers QPC', layer: 'de_jure' },
        { from: 'cc', to: 'parliament', label: 'strikes unconstitutional provisions', layer: 'de_jure' },
      ],
      notes: ['France combines ex ante review with ex post QPC review.'],
      sources: [
        baseSources.frConstitution,
        { title: 'Conseil constitutionnel - QPC', url: 'https://www.conseil-constitutionnel.fr/en/question-prioritaire-de-constitutionnalite-qpc' },
        { title: 'Conseil d’État', url: 'https://www.conseil-etat.fr/en' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'election_representation',
      title: 'Election and Representation Diagram',
      purpose: 'How votes are converted into presidential and assembly representation.',
      level: 2,
      nodes: [
        { id: 'voters', label: 'Voters', category: 'Voters / Citizens' },
        { id: 'parties', label: 'Parties and Alliances', category: 'Political Party' },
        { id: 'president', label: 'President', category: 'Executive Office' },
        { id: 'constituencies', label: 'Legislative Constituencies', category: 'Subnational Government' },
        { id: 'assemblee', label: 'National Assembly', category: 'Legislative Chamber' },
        { id: 'interior', label: 'Interior Ministry', category: 'Ministry / Department' },
      ],
      edges: [
        { from: 'voters', to: 'president', label: 'two-round direct election', layer: 'de_jure' },
        { from: 'voters', to: 'constituencies', label: 'two-round legislative ballots', layer: 'de_jure' },
        { from: 'constituencies', to: 'assemblee', label: 'elect one deputy each', layer: 'de_jure' },
        { from: 'parties', to: 'assemblee', label: 'alliance strategy affects seat conversion', layer: 'de_facto' },
        { from: 'interior', to: 'president', label: 'organizes and certifies results', layer: 'de_jure' },
        { from: 'interior', to: 'assemblee', label: 'organizes and certifies results', layer: 'de_jure' },
      ],
      notes: ['Two-round system incentivizes alliance bargaining between rounds.'],
      sources: [
        { title: 'Code électoral (Légifrance)', url: 'https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000006070239/' },
        { title: 'French Interior Ministry - Elections', url: 'https://www.interieur.gouv.fr/Elections' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'territorial_federalism',
      title: 'Territorial and Decentralization Diagram',
      purpose: 'Power distribution in a unitary but decentralized French state.',
      level: 2,
      nodes: [
        { id: 'state', label: 'Central State', category: 'Executive Office' },
        { id: 'parliament', label: 'Parliament', category: 'Legislature' },
        { id: 'regions', label: 'Regions', category: 'Subnational Government' },
        { id: 'departments', label: 'Departments', category: 'Subnational Government' },
        { id: 'communes', label: 'Communes', category: 'Subnational Government' },
        { id: 'prefects', label: 'Prefects', category: 'Executive Office' },
      ],
      edges: [
        { from: 'parliament', to: 'regions', label: 'defines competences', layer: 'de_jure' },
        { from: 'parliament', to: 'departments', label: 'defines competences', layer: 'de_jure' },
        { from: 'parliament', to: 'communes', label: 'defines competences', layer: 'de_jure' },
        { from: 'state', to: 'prefects', label: 'appoints territorial representatives', layer: 'de_jure' },
        { from: 'prefects', to: 'regions', label: 'legality control', layer: 'de_jure' },
        { from: 'prefects', to: 'departments', label: 'legality control', layer: 'de_jure' },
      ],
      notes: ['France remains unitary; decentralization is extensive but not federal sovereignty.'],
      sources: [baseSources.frConstitution, { title: 'Collectivités locales', url: 'https://www.collectivites-locales.gouv.fr/' }],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'budget_finance',
      title: 'Budget and Public Finance Diagram',
      purpose: 'Budget drafting, parliamentary vote, and expenditure control in France.',
      level: 2,
      nodes: [
        { id: 'taxpayers', label: 'Taxpayers', category: 'Voters / Citizens' },
        { id: 'financeMin', label: 'Ministry of Economy and Finance', category: 'Ministry / Department' },
        { id: 'government', label: 'Government', category: 'Executive Office' },
        { id: 'assemblee', label: 'National Assembly', category: 'Legislative Chamber' },
        { id: 'senate', label: 'Senate', category: 'Legislative Chamber' },
        { id: 'courDesComptes', label: 'Cour des comptes', category: 'Independent Agency' },
      ],
      edges: [
        { from: 'taxpayers', to: 'financeMin', label: 'provide revenues', layer: 'de_jure' },
        { from: 'financeMin', to: 'government', label: 'drafts finance bill', layer: 'de_jure' },
        { from: 'government', to: 'assemblee', label: 'submits finance bill first', layer: 'de_jure' },
        { from: 'assemblee', to: 'senate', label: 'transmits adopted text', layer: 'de_jure' },
        { from: 'senate', to: 'assemblee', label: 'amends and returns', layer: 'de_jure' },
        { from: 'courDesComptes', to: 'government', label: 'audits execution', layer: 'de_jure' },
      ],
      notes: ['Annual finance-law timelines are constitutionally constrained.'],
      sources: [
        { title: 'LOLF 2001', url: 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000392989' },
        baseSources.frConstitution,
        { title: 'Cour des comptes', url: 'https://www.ccomptes.fr/en' },
      ],
      lastUpdated: '2026-04-21',
    },
    {
      id: 'de_facto_power',
      title: 'De Facto Power Map',
      purpose: 'Practical influence beyond constitutional text in the semi-presidential system.',
      level: 2,
      nodes: [
        { id: 'president', label: 'President and Elysee', category: 'Executive Office' },
        { id: 'pm', label: 'Prime Minister/Matignon', category: 'Executive Office' },
        { id: 'partyBlocs', label: 'Parliamentary Blocs', category: 'Political Party' },
        { id: 'civilService', label: 'Senior Civil Service', category: 'Independent Agency' },
        { id: 'media', label: 'Public Opinion and Media', category: 'Voters / Citizens' },
      ],
      edges: [
        { from: 'president', to: 'pm', label: 'sets strategic line outside cohabitation', layer: 'de_facto' },
        { from: 'partyBlocs', to: 'pm', label: 'controls legislative survival margin', layer: 'de_facto' },
        { from: 'civilService', to: 'pm', label: 'agenda filtering and implementation leverage', layer: 'de_facto' },
        { from: 'media', to: 'president', label: 'approval pressure on agenda', layer: 'de_facto' },
      ],
      notes: ['Confidence: medium-high. Presidential dominance varies with assembly arithmetic.'],
      sources: [
        { title: 'Vie publique - Institutions', url: 'https://www.vie-publique.fr/' },
        { title: 'Elysee - Role of the President', url: 'https://www.elysee.fr/en/french-presidency/the-role-of-the-president-of-the-republic' },
      ],
      lastUpdated: '2026-04-21',
    },
  ],
};

export const COUNTRY_POLITICAL_PROFILES: Record<string, CountryPoliticalProfile> = {
  CH: switzerlandProfile,
  DE: germanyProfile,
  GB: ukProfile,
  UK: ukProfile,
  US: usProfile,
  FR: franceProfile,
  PT: portugalProfile,
  ES: spainProfile,
};
export function getCountryPoliticalProfile(countryCode: string | undefined) {
  if (!countryCode) return null;
  return COUNTRY_POLITICAL_PROFILES[countryCode.toUpperCase()] || null;
}
